### ISSUE TITLE
Astropy's NDData arthmetic buggy in current release

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#100]
The arithmetic mixin and nddata objects have several bugs that are fixed in the development branch of astropy, but not in the release.

I previously had several workarounds, but they were not robust enough to prevent errors. I've disabled the arithmetic for now. I'm pasting a reproducible bug error below for the current version of astropy (I had began to write a PR, but realized they fixed this in the development branch).

``` python
class TestData(NDData):
    def __init__(*args, **kwargs):
        super(TestData, self).__init__(*args, **kwargs)

a = NewData(np.random.sample(10), uncertainty=StdDevUncertainty(np.random.sample(10)*0.1))
b = NewData(np.random.sample(10), uncertainty=StdDevUncertainty(np.random.sample(10)*0.1))
c = a.multiply(b)

/Users/nearl/local/lib/python2.7/site-packages/astropy/nddata/mixins/ndarithmetic.pyc in _arithmetic(self, operand, propagate_uncertainties, name, operation)
/Users/nearl/local/lib/python2.7/site-packages/astropy/nddata/nduncertainty.pyc in propagate_multiply(self, other_nddata, result_data)
/Users/nearl/local/lib/python2.7/site-packages/astropy/nddata/nduncertainty.pyc in parent_nddata(self)
MissingDataAssociationException: Uncertainty is not associated with an NDData object
```

**Comment by nmearl** [comment]
As @pllim pointed out, it's alright if we use development version of astropy for now. I've re-enabled arithmetic, and added the dev version to the install requirements in d606e8f794a66b540a53655a1f125964abe602b6.

**Comment by pllim** [comment]
Might want to note that in user-facing documentation about installation too.

**Comment by eteq** [comment]
:+1: to making sure users know that they need the dev version.

@pllim - are these fixes to actual bugs?  I.e., a 1.1.2 release will fix them?  Or "buggy" in the sense of some substantial behavior change that has to wait for 1.2?

**Comment by eteq** [comment]
(In case it's not clear, the relevance of that question is that a 1.1.2 release can occur very soon, like probably next week.  But 1.2 isn't until the summer)

**Comment by pllim** [comment]
@eteq , not sure. I am not following Astropy NDData development very closely. But given that Pyfocal is likely to remain in alpha (or maybe beta?) stage in summer anyway, I don't think this is a huge issue since we have a workaround by using dev.

What do you think, @nmearl ?

**Comment by eteq** [comment]
If you could trace down where this is fixed that would be helpful.  Possibly if it's something marginal (sort of bug sort of feature) and we have it slated for 1.2, we *could* backport it to 1.1.x .  The bug/feature line is often pretty grey, anyway.

**Comment by pllim** [comment]
Maybe @nmearl can do this when he get the chance, since he was the one encountered it. Nick, if you go to that file in Astropy repo and click blame, you should be able to find the exact commit/author.

**Comment by nmearl** [comment]
@eteq It's affected by the infrastructure of how `NDData` objects interact with `NDUncertainty` objects. It's not a "bug" perse, maybe more of a systemic error.

This has been fixed in a giant refactoring effort back in October. However, the current astropy sports the September version of the files.

Because of the above, it's not really something a simple blame is going to highlight.

**Comment by pllim** [comment]
Is it astropy/astropy#4272 ? The title sounds like what you described.

**Comment by pllim** [comment]
Yeah, I think that definitely has to wait till 1.2.

**Comment by eteq** [comment]
Ohh, gotcha.  Yeah, in that case the timescale is probably end of spring or summer, sadly...  

One option is to package the new `nddata` in an `extern` right now, and when using it in `pyfocal`, wrap everything in something like:
```
def compat_NDData(*args,**kwargs):
    if astropy.__version__ < 1.1.x # there's a distutils thing to do this, but I can't remember the syntax off the top of my head...
        return extern.NDData(*args, **kwargs)
    else:
        return astropy.nddata.NDData(*args, **kwargs)
```
That's a standard pattern we use in affiliated packages or in astropy (when some other dependency is the problem).

**Comment by nmearl** [comment]
With the update to astropy, this is no longer an issue.
