### ISSUE TITLE
Make double-clicking on the dataset show the spectrum?

### ISSUE THREAD

**Issue by eteq** [spacetelescope/specviz#103]
Not particularly high-priority, but worth considering:  My instinct was to double-click on the name of the dataset in the "Data" box to get it to come up.  I keep doing that and then remembering I have to click the icon on the bottom-left.  Can the double-click behavior be made to happen?  I realize this overlaps with the "rename" function currently in there, but for me, at least, "show the spectrum" is higher priority than "rename the dataset"

**Comment by hcferguson** [comment]
+1 for this, but obviously would need to retain the ability to rename the dataset somehow.

**Comment by nmearl** [comment]
Hmm. It'd be weird. Either we can move the rename functionality to a context menu option, or implement something like Glue where you can drag the data object into your plot area to plot. In the former case, this would have to propagate through layer, models, and model parameters to be consistent

**Comment by eteq** [comment]
Hmm, what about *single-click* shows the plot, but double-click does the rename mode? Or is there some need to be able to select a dataset without showing it?

**Comment by nmearl** [comment]
Well, two buttons at the bottom of the data window are supposed to be "Create new window" and "Add to current window". How would the user choose which action to perform? What would be the default action?

**Comment by pllim** [comment]
> Hmm, what about single-click shows the plot, but double-click does the rename mode?

That would be contrary to people who are used to computer file system, where single-click is rename and double-click is launch.

**Comment by eteq** [comment]
@nmearl - I would say the default click behavior would be to create a new window if *no* window exists, and add to existing if there is one currently active.

@pllim - ok, then maybe single-click to rename and double-click to show the data?  

My main underlying concern is that two clicks in different places is rather counter-intuitive when I just want a "quick look".  This might be obviated anyway by behavior that auto-shows the spectrum if there's just one, though. (I think there's an issue for that?  Or maybe a trello card?)
