### ISSUE TITLE
Ctrl-C and then GUI interaction causes crashes

### ISSUE THREAD

**Issue by eteq** [spacetelescope/specviz#104]
Also not high priority, but I figured I'd report this:  If I Ctrl-C in the console window that I started pyfocal from, nothing happens (presumably because python is in the Qt event loop and sleeping or something).  But if I then interact with the GUI, it spits out random errors, and usually the GUI shortly after hard-crashes.  Perhaps there's some way to catch the exceptions Ctrl-C generates and use them to either "safely" close the GUI, or just block them completely?

**Comment by pllim** [comment]
What was your purpose pressing Ctrl+C in the first place?

**Comment by eteq** [comment]
To close the app.  I expect plenty of users will have that instinct if they're invoking it from the command line because it usually does :tm: . Not critical to have that work, but definitely should at least do *something* if it's easy.

**Comment by pllim** [comment]
That's interesting. Because I never even thought about using Ctrl+C to close a GUI. I always just press the X, or "Quit" from menu, or Alt+F4. :smile:

**Comment by pllim** [comment]
Or power button, in extreme cases. :ghost:

**Comment by eteq** [comment]
In my mind "if I open it from a terminal, use Ctrl-C, if I open it from an icon, use x/quit/alt-f4/cmd-Q etc".  It's rather irrational, but I know other users who have a similar instinct...

**Comment by pllim** [comment]
@eteq , I can't reproduce the crash on Anaconda/Qt4/RHEL6. Do you have a specific workflow to recreate this?

**Comment by eteq** [comment]
@pllim: this seems to repeatedly work for me, although I'm on Anaconda/Qt5/OS X 10.10 (Yosemite):

1. Start `specviz` with a file e.g., ``specviz example_spec_ascii.txt``
1. Wait for the GUI to start up
1. Go back to the terminal, and ctrl-C
1. Click the "Create new plot window from data"(although I think other interactions will also do it)
1. Nothing happens in the GUI for ~2 sec, although the terminal immediately prints out a traceback with a `KeyboardInterrupt`.
1. After a few seconds, the specviz GUI crashes with a "python quit unexpectedly." dialog.

**Comment by eteq** [comment]
I do have a suspicion this is a platform-specific issue, although it might instead be a qt4/5 problem.  If I get a chance later I might try my linux VM at home and see if I can get the same behavior there on qt5.

**Comment by pllim** [comment]
Ah okay. I can reproduce now. Fix merging shortly.

http://stackoverflow.com/questions/4938723/what-is-the-correct-way-to-make-my-pyqt-application-quit-when-killed-from-the-co

**Comment by pllim** [comment]
@eteq , does #183 fix this for you? Now when you interact with GUI, it will exit more gracefully next time `signal` process the OS signals.

**Comment by eteq** [comment]
Aha, yep, in master I know get a: ``WARNING: KeyboardInterrupt caught; specviz will terminate [specviz.app]`` message. Thanks, @pllim!

The one remaining quibble is that it doesn't close until there's a GUI interaction, and even better would be for it to be killed immediately upon the ctrl-C.  But I'm pretty sure that's because of how pyqt's even loop works, so I'm guessing there's just nothing to be done about it without hacking qt, certainly beyond the scope of this issue!

**Comment by pllim** [comment]
Yeah, event loop signals are in a different world from the OS system signals. Glad that works for you.
