### ISSUE TITLE
Layer arithmetic has unit ramification

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#106]
Having finished implemented unit changing, I've now noticed that Pyfocal will crash when the quotient or product of an arithmetic operation results in different units (due to the values being `Quantities`). It will try to plot something with `flux ** 2` onto a plot with units in `flux` and fail to convert.

This will require forcing the result of the calculation to use the units of one of the operands.

**Comment by hcferguson** [comment]
My gut reaction is to not allow calculations that result in a change of units in this tool. However I note that splot does include logarithms and exponentiation.

**Comment by ibusko** [comment]
In other projects I worked (Aspect, Java specview, Iris), the way to deal with this is to use an intermediate units conversion to and from a hidden, "internal", common units set. First, one converts both spectra from their native units into this internal set (say, Angstrom and flam). Then one performs the operation. And then convert the result back from the "internal" set to a set of "user units" that the user can define, say, in a preferences file. All this takes place with the user being aware of it.

This gives the user control on what units to have the result expressed on. If not defined by the user, this "user units" is set by default to identical with the "internal units".

**Comment by nmearl** [comment]
@ibusko The issue is not that the units don't match -- Astropy will auto-convert for a calculation -- it's that the units are incompatible.

If you perform a multiplicative layer calculation, you end up with units in e.g. `Anstrom ** 2` and `flam ** 2`; or say you divided two layers, you now have a new layer with no units. This has a couple of problems:

1. The plot sub window maintains its own set of units, the "displayed units" then can be changed by the user. When you plot a layer, the layer values are converted into these "displayed units". Currently, it disallows you from displaying layers that are quotients or products because the units are incompatible.

2. This is a compounded issue with future arithmetic calculations using the results of previous arithmetic calculations.

I can force compatible units for the sake of displaying the plot, but they would be incorrect for the data that is shown.

**Comment by hcferguson** [comment]
A possible workaround would be to throw an error if a calculation would change the units, but also provide the ability (which we already have, right?) for the user to make one of the operands dimensionless. Then we would just put in the documentation that if you want to, e.g., multiply one spectrum by another, you need to make the flux units of one of them dimensionless (at least temporarily). 

Similarly, if they want to exponentiate or take a log (e.g. of some sort of ad-hoc model they are wanting to subtract), then they need to remove the units. They can assign units back to the resulting spectrum if they want. This forces them to think about it. I don't think this is common enough to provide a shortcut for this workflow, but if it turns out to be common, it presumably wouldn't be hard to add such a shortcut.

**Comment by hcferguson** [comment]
@nmearl What are you doing in the arithmetic calculations when the two spectra aren't gridded the same way in wavelength, or cover different wavelength ranges?  Adopting the wavelength grid of the first spectrum and interpolating the second? If so, we need to document what interpolation algorithm we are using and make it easy to change that or offer several options as we evolve the tool. Similarly for places where the two spectra overlap, for now we could throw an error, but downstream we will want to provide some options for how to extrapolate if the spectra don't overlap, or whether to just make the result NaNs at those wavelengths.

**Comment by pllim** [comment]
@hcferguson , this is where `pysynphot` might come in handy (as I asked in #22), as it already handles unit conversion, wavelength interpolation, etc all behind the scenes. Let's becareful not to reinvent the wheel here.

**Comment by pllim** [comment]
About log-scale plotting for Y-axis... Isn't `log(flux)` representing its magnitude? It would be less confusing to just plot in magnitude then. Just plainly plot `log(flux)` does not really mean anything.

**Comment by ibusko** [comment]
I have seen a lot of log-Y plot scaling in astronomical spectra. Maybe not common in the UV-IR range, but radio and high energy folks are very used to it. They don't use magnitudes btw. Unless we are restricting specviz to the more limited range, I believe log-Y should be a valid option. 

And also log-X should be available, unless, again, we are restricting specviz to limited wavelength ranges.

**Comment by hcferguson** [comment]
Log flux is used very commonly. I would offer magnitude separately.

**Comment by hcferguson** [comment]
@pllim I agree that we should look at and possibly adopt pysynphot's approach. Certainly shouldn't re-invent without a good reason! Also, it's unclear to me whether the new ETC is using pysynphot for spectrum arithmetic or doing something else.

**Comment by pllim** [comment]
Regarding ETC, we can probably as @tepickering

**Comment by nmearl** [comment]
@hcferguson It's disconnected at the moment (meaning arithmetic only works on same-shape arrays). SpecView was only marginally more sophisticated in that it would to perform a simple one-dimensional piecewise linear interpolation, but would not try to re-grid data.

I have a simple grid matrix generator for transforming spectra I've implemented elsewhere, but I get the impression that pysynphot is probably more robust for our situation.

**Comment by pllim** [comment]
PySynphot is fully documented at http://ssb.stsci.edu/pysynphot/docs/ if you wish to see if it fits your needs. FYI.

**Comment by nmearl** [comment]
Well, immediately, the biggest problem with pysynphot would be

> pysynphot is currently incompatible with Python 3.

**Comment by hcferguson** [comment]
I don't think we want to build a pysynphot dependency. But we may be able to grab some code.

**Comment by pllim** [comment]
Actually, that disclaimer is a bit outdated. I just updated the text today but it won't be on the server till tomorrow. @bernie-simon actually added Python 3 support to it a few months back, but the catch is that that version (0.9.8) is not on PyPi, so you have to install from source (since you don't use `stsci_python` nor Ureka).

But yeah, I have no objection if you want to grab pieces of it for this software, since this is all from the same organization and under the same license etc.

**Comment by nmearl** [comment]
This is no longer an issue. Arithmetic operations now result in new sub windows.
