### ISSUE TITLE
specviz vs specview 

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#119]
Now that both `specviz` and `specview` are in `spacetelescope`, we need to be clear on which one user is supposed to use, to avoid confusion. Maybe renamed `specview` to `specview_DONOTUSE` or something?

c/c @ibusko

**Comment by ibusko** [comment]
I'm fine with renaming to anything. Maybe specview_old_DONOTUSE to make clear it's the older code?

**Comment by nmearl** [comment]
No, that won't work. Currently, the SpecView I started (as opposed to the Java one that Ivo started), along with CubeTools is still used with Glue for the MOSTools stuff.

Its name needs to stay the same.

**Comment by pllim** [comment]
Hmm. Will `specview` remain in use in Glue? Or eventually to be replaced by `specviz`? At least the README in `specview` can have text like, "For use in Glue only" or something...

**Comment by nmearl** [comment]
I don't think there are plans currently to replace the Glue tools. I'm not sure what the future of the MOSTools is (do we move it into SpecViz?) Maybe @hcferguson can speak to that.

**Comment by justincely** [comment]
specview is no longer used, and has been removed from the Astroconda distribution entirely.  Not sure if we want to keep the repo around anymore, but that can be discussed in it's own repo.
