### ISSUE TITLE
Explore using qtawesome instead of image icons

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#12]
See [here](https://github.com/spyder-ide/qtawesome). Using font awesome's glyphs instead of image icons for qt elements.

**Comment by pllim** [comment]
I would rather not add yet another dependency to `pyfocal` just to have "awesome" icons. Also, some people do not like animated icons.

**Comment by pllim** [comment]
Closing. Feel free to reopen if needed.
