### ISSUE TITLE
Access for Harry

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#120]
@hcferguson , do you still have permission issue with `specviz` being in `spacetelescope` repo?

**Comment by hcferguson** [comment]
Testing one two three four...

**Comment by hcferguson** [comment]
Successfully installed specviz if that was really the question...

**Comment by pllim** [comment]
@hcferguson , during sprint tag up last week, you mentioned that there were some things that you were unable to do because the codes are in Nick's repo, not `spacetelescope`. That is why we moved it here, right? Can you do those things now?

**Comment by hcferguson** [comment]
@plim Ah. Right...that was trying to create an issue from a Trello card or a Trello card from an issue. I'll give it a try.

**Comment by hcferguson** [comment]
@plim -- interestingly, I can see most of the spacetelescope repos in zapier (that tool that integrates lots of these cloud services), but it doesn't manage to find spacetelescope/specviz .

**Comment by pllim** [comment]
@hcferguson , I added you as a collaborator in `specviz`. Can you refresh and check again?

If that does not work, I also see a "Trello" webhook I can attach to `specviz`. It says "works with perspective".

**Comment by nmearl** [comment]
@pllim While you're at it, you may want to add a webhook for read the docs. The new docs are here: http://specviz.readthedocs.org and are associated with the ST repo.

Also, I cannot edit the tag line at the top of the repo page. Can you update the RTD website there as well?

**Comment by pllim** [comment]
@nmearl , RTD webhook and repo tagline fixed. On the next commit, see if RTD auto builds.

I am going to hold off Trello webhook until I hear back from @hcferguson .
