### ISSUE TITLE
specviz installation error

### ISSUE THREAD

**Issue by gderosa2004** [spacetelescope/specviz#122]
I have cloned the specviz dir, and tried to install it but getting the following error. 

> $ pip install -r requirements
> Installing collected packages: MarkupSafe, jinja2, cython, astropy, Pyfocal
>   Found existing installation: astropy 1.1.1
>     Uninstalling astropy-1.1.1:
>       Successfully uninstalled astropy-1.1.1
>   Running setup.py install for astropy ... done
>   Running setup.py develop for Pyfocal
>     Complete output from command /Users/gderosa/anaconda/envs/py35/bin/python -c "import setuptools, tokenize;__file__='/Users/gderosa/specviz/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
>     running develop
>     running build_py
>     running egg_info
>     error: error in 'egg_base' option: '/Users/gderosa/specviz/build/lib.macosx-10.5-x86_64-3.5' does not exist or is not a directory
>     
>     ----------------------------------------
> Command "/Users/gderosa/anaconda/envs/py35/bin/python -c "import setuptools, tokenize;__file__='/Users/gderosa/specviz/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/gderosa/specviz

**Comment by pllim** [comment]
Are you `specviz` source codes at `'/Users/gderosa/specviz/`? If so, try run `python setup.py build` in that directory and try again.

**Comment by gderosa2004** [comment]
Yes, that’s were source codes are. I’ve tried, got same error


(py35)bash-3.2$ python setup.py build

running build

(py35)bash-3.2$ pip install -r requirements.txt

Collecting git+https://github.com/nmearl/astropy.git (from -r requirements.txt (line 5))

  Cloning https://github.com/nmearl/astropy.git to /var/folders/mq/5zr2tpc15m35ymqm8nqqgf0r0001_y/T/pip-j09yr164-build

  Requirement already satisfied (use --upgrade to upgrade): astropy==1.1.dev14590 from git+https://github.com/nmearl/astropy.git in /Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages (from -r requirements.txt (line 5))

Collecting git+https://github.com/nmearl/pyqtgraph.git (from -r requirements.txt (line 6))

  Cloning https://github.com/nmearl/pyqtgraph.git to /var/folders/mq/5zr2tpc15m35ymqm8nqqgf0r0001_y/T/pip-7c8m0dzx-build

  Requirement already satisfied (use --upgrade to upgrade): pyqtgraph===pyqtgraph-0.9.10-144-g652d607 from git+https://github.com/nmearl/pyqtgraph.git in /Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages (from -r requirements.txt (line 6))

Obtaining file:///Users/gderosa/specviz (from -r requirements.txt (line 7))

Requirement already satisfied (use --upgrade to upgrade): jinja2 in /Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages (from -r requirements.txt (line 3))

Requirement already satisfied (use --upgrade to upgrade): cython in /Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages (from -r requirements.txt (line 4))

Requirement already satisfied (use --upgrade to upgrade): numpy>=1.6.0 in /Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages (from astropy==1.1.dev14590->-r requirements.txt (line 5))

Requirement already satisfied (use --upgrade to upgrade): PyYAML in /Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages (from Pyfocal==0.1a1->-r requirements.txt (line 7))

Requirement already satisfied (use --upgrade to upgrade): scipy in /Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages (from Pyfocal==0.1a1->-r requirements.txt (line 7))

Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages (from jinja2->-r requirements.txt (line 3))

Installing collected packages: Pyfocal

  Running setup.py develop for Pyfocal

    Complete output from command /Users/gderosa/anaconda/envs/py35/bin/python -c "import setuptools, tokenize;__file__='/Users/gderosa/specviz/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:

    running develop

    running build_py

    running egg_info

    error: error in 'egg_base' option: '/Users/gderosa/specviz/build/lib.macosx-10.5-x86_64-3.5' does not exist or is not a directory



    ----------------------------------------

Command "/Users/gderosa/anaconda/envs/py35/bin/python -c "import setuptools, tokenize;__file__='/Users/gderosa/specviz/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/gderosa/specviz

(py35)bash-3.2$

**Comment by pllim** [comment]
I see "requirement already satisfied" in the traceback. So let's try skip that pip stuff now and just run
```
python setup.py install
```
Does it work?

**Comment by gderosa2004** [comment]
Yes, python setup.py install works.

But then I get error when I call pyfocal:


(py35)bash-3.2$

(py35)bash-3.2$ pyfocal

Traceback (most recent call last):

  File "/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 640, in _build_master

  File "/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 941, in require

  File "/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 833, in resolve

pkg_resources.ContextualVersionConflict: (astropy 1.1.dev14590 (/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages), Requirement.parse('astropy>=1.1'), {'Pyfocal'})


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/gderosa/anaconda/envs/py35/bin/pyfocal", line 5, in <module>

    from pkg_resources import load_entry_point

  File "<frozen importlib._bootstrap>", line 969, in _find_and_load

  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible

  File "/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 3140, in <module>

  File "/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 3126, in _call_aside

  File "/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 3153, in _initialize_master_working_set

  File "/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 642, in _build_master

  File "/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 655, in _build_from_requirements

  File "/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 828, in resolve

pkg_resources.DistributionNotFound: The 'astropy>=1.1' distribution was not found and is required by Pyfocal

**Comment by nmearl** [comment]
The call is now `specviz` instead of `pyfocal`. Try typing `specviz` at the command line instead of `pyfocal`.

**Comment by pllim** [comment]
@nmearl , I don't see any `scripts` folder in the repo. Where is the script now?

**Comment by gderosa2004** [comment]
(py35)bash-3.2$ specviz

Traceback (most recent call last):

  File "/Users/gderosa/anaconda/envs/py35/bin/specviz", line 9, in <module>

    load_entry_point('specviz==0.1.0a1.dev228', 'console_scripts', 'specviz')()

  File "/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 547, in load_entry_point

  File "/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 2719, in load_entry_point

  File "/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 2379, in load

  File "/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 2385, in resolve

ImportError: No module named 'specviz'

**Comment by nmearl** [comment]
@pllim what do you mean `scripts` directory?

**Comment by gderosa2004** [comment]
>  specviz
> Traceback (most recent call last):
>   File "/Users/gderosa/anaconda/envs/py35/bin/specviz", line 9, in <module>
>     load_entry_point('specviz==0.1.0a1.dev228', 'console_scripts', 'specviz')()
>   File "/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 547, in load_entry_point
>   File "/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 2719, in load_entry_point
>   File "/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 2379, in load
>   File "/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/pkg_resources/__init__.py", line 2385, in resolve
> ImportError: No module named 'specviz'

**Comment by pllim** [comment]
Usually, any executable script is stored in `scripts`. That's how I see `setup.py` has it set up. But if it is not there, where is the executable script in the repo?

**Comment by nmearl** [comment]
As per astropy affiliate style, the reference to console scripts is placed in `setup.cfg`.

**Comment by pllim** [comment]
Ah, okay. I am able to install it okay but I am not using Python 3.5 env.

**Comment by pllim** [comment]
@gderosa2004 , make sure that `specviz` was actually installed in the correct environment. Can you see it under `/Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages/`? Try:
```
$ ls /Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages | grep specviz
```

**Comment by gderosa2004** [comment]
I have also tried in my standard env and is not working

**Comment by gderosa2004** [comment]
```
$ ls /Users/gderosa/anaconda/envs/py35/lib/python3.5/site-packages | grep specviz
specviz-0.1.0a1.dev228-py3.5.egg
```

**Comment by pllim** [comment]
Gisella will try again from a fresh Anaconda environment and give us an update.

**Comment by gderosa2004** [comment]
This is getting really weird.. -_-

I've tried everything in a clean environment. 
cloned directory, ran 
 ` pip install -r requirements.txt `
Everything went fine. Got the following error when launching specviz:
`ImportError: No module named 'yaml'`
Since the same thing happened with pyfocal, I did:
`conda install yaml`
reopened the window, launched specviz, got the same error:
`ImportError: No module named 'yaml'`

HELP??!

**Comment by nmearl** [comment]
> reopened the window, launched specviz, got the same error:

Did you first start your virtual environment before you ran `specviz` again?

**Comment by gderosa2004** [comment]
yep.. 
`(sviz_env)bash-3.2$ specviz`

**Comment by pllim** [comment]
That is included in Anaconda. Try
```
conda install yaml
```

**Comment by pllim** [comment]
Oh wait, sorry, I missed the message above.

**Comment by pllim** [comment]
Try
```
conda install pyyaml
```

**Comment by gderosa2004** [comment]
yeah, that's the first thing I've tried

**Comment by gderosa2004** [comment]
`conda install pyyaml`

worked!! How is it possible that I am having all these issues?!!
I can open specviz now, but lost my testing time this afternoon :-(

I'll try to find some time before we meet tomorrow..
