### ISSUE TITLE
Make selections (ROIs?) drag-out-able

### ISSUE THREAD

**Issue by eteq** [spacetelescope/specviz#123]
I'm not sure what the right word is for this behavior, but what I have in mind here is some way to "drag out" the span selections.  Right now, clicking creates a region, which I then have to move and resize (two operations), but it would be nice if there were an _option_ to instead drag click and drag in the plot, and get a span that fills the horizontal extent.  I can see use cases where _either_ interaction is more natural, but for at least some of mean, the single click (or at least a click-drag-release) is more efficient.

(Sorry if this is in some other issue or card already that I missed... Feel free to close this if so.)

**Comment by hcferguson** [comment]
@eteq Seems like this can be closed?
