### ISSUE TITLE
Make spam/ROI button create a singleton?

### ISSUE THREAD

**Issue by eteq** [spacetelescope/specviz#124]
Right now when I click the ROI button to get a span, if I keep clicking this, I get multiple ROIs, but now clear sign of how to differentiate them.  Maybe ROIs should be singletons, and only get persistence when tied to a model or a layer or something?

This also might just be a bug, in which case this is a bug report, not a feature request ;)

**Comment by nmearl** [comment]
As discussed on 2/24, a singleton is probably not effective enough and preemptively carving out use cases will hurt us later on.

**Comment by eteq** [comment]
Yep, that makes sense. Still need to make it clearer which is there "active" region, but that's probably best treated separately.

PS the title of this is supposed to be "make span", not " make spam"... But probably best to leave it alone for comedic effect ;)
