### ISSUE TITLE
Data trash can not working

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#125]
The trashcan associated with the data window doesn't seem to do anything.

**Comment by nmearl** [comment]
Yeah. I disconnected it. Previously, it was defaulting to deleting any layer also associated with the data object. Wasn't sure if that was the wanted behavior, but didn't want to deal with it at the moment. 

I assume we want to keep layers created using the data? If that's the case, the actual data needs to be preserved while the gui object needs to be deleted.

**Comment by nmearl** [comment]
Implemented in f8dd23ed62bc0507f376e7286c5298dee773b884.
