### ISSUE TITLE
make default color of first plot black

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#127]
The color of the first plot comes out light blue for me. Sort of hard to see on my retina screen, since it's such a thin line.

**Comment by nmearl** [comment]
It's a random color every time it's plotted. We can limit the random pool (currently it could be any combination of RGB values).

**Comment by hcferguson** [comment]
There is a 15-color palette that is colorblind friendly at http://www.somersault1824.com/tips-for-designing-scientific-figures-for-color-blind-readers/. Perhaps just cycling through that might make sense? Repeating colors after 15 doesn't seem like crime to me, since the user can change them anyway.

**Comment by nmearl** [comment]
Added in #135. Check it out and reopen if you're still seeing an issue.

**Comment by pllim** [comment]
This default color does not apply when user opens another file in the same session.

**Comment by justincely** [comment]
After looking at this in the sprint, the default color is black on the first spectrum plotted, but subsequent loads will not start over to black.  This should be changed.

We should also examine the color palette chosen and see if it's optimal: colorblindness, etc

**Comment by nmearl** [comment]
(This is a test for GitHub bot integration) Plot colors are very useful -- we should explore the best color sets to utilize.
