### ISSUE TITLE
Inconsistent behavior of Region vs. equivalent-width selection

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#128]
Not a bug....just something to think about. 
- clicking the equivalent-width selection button toggles the regions on and off
- clicking the ROI rectangle creates new ones

**Comment by nmearl** [comment]
What do you mean?

**Comment by nmearl** [comment]
Removed the "mode" behavior, and replaced it with a simplified requirement of having to have at least three ROIs on the plot before measured statistics become active.
