### ISSUE TITLE
Move model "Update layer"  or "Create Layer" up

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#130]
Right now "Create Layer" is scrolled off the screen after I select a model, so my instinct is to push "Load," which of course isn't right. 

One solution is to have small icon-buttons here instead of the words and put them all together. I think it might be relatively intuitive to use a "refresh" icon for "Create Layer" and "Update Layer" and then "save to disk" and "load to disk" icons for the others. That will save real-estate.

**Comment by pllim** [comment]
Another option is to have an "expander" widget. This way, the "modeling" section can be hidden when not needed, and so can "statistics". I imagine the typical workflow would be:

1. Hide statistics to get the models right.
2. Hide models and expand statistics to look at the values.

http://stackoverflow.com/questions/10364589/equivalent-of-gtks-expander-in-pyqt4

p.s. Implemented in Ginga as `ginga.gw.Widgets.Expander()`.

**Comment by nmearl** [comment]
There are several unofficial implementations of an [accordion widget](https://en.wikipedia.org/wiki/Accordion_%28GUI%29) in pyqt. Here's [one for pyqt5](https://github.com/crapp/qaccordion). But I'm not sure I want to trust custom implementations. Perhaps a [ToolBoxWidget](http://doc.qt.io/qt-4.8/images/designer-containers-toolbox.png) is better suited. 

The idea behind using DockWidgets is that they can be "popped" in and out to allow the plot window area to expand for more real estate.

**Comment by nmearl** [comment]
This is no longer relevant.
