### ISSUE TITLE
How to handle flux unit electrons/s

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#136]
Some data has
```python
BUNIT = 'ELECTRONS/S'
```
but Astropy does not recognize it. `specviz` needs to auto-magically correct that somehow.

**Comment by nmearl** [comment]
Can we define some special equivalencies or something, and add them to some type of astropy unit conversion registry?

**Comment by pllim** [comment]
That might work but would be overkill. I was thinking just adding an `if-else` hack in `loaders.py` within `_flux_unit_from_header()` function. Is that alright or too hacky?

**Comment by nmearl** [comment]
No, no, that's perfectly fine!
