### ISSUE TITLE
Test of creating a Github issue from Trello

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#137]

**Comment by hcferguson** [comment]
Didn't quite work...It was supposed to pull in the description.
I'll have to try again...

**Comment by pllim** [comment]
Do you use "perspective"? If so, I can enable the Trello webhook. Let me know.

**Comment by hcferguson** [comment]
Hmm....I'm using Zapier, but it's capabilities seem pretty limited. It doesn't look like it can mirror the comment stream back to Trello. And it doesn't look like it provides a link on the Trello card back to the issue. So "perspective" might be worth a look. Looks like it might require a paid or enterprise Trello account though. Zapier is free as long as the volume is low.

**Comment by pllim** [comment]
Ah, okay. I cannot find any webhook that says "Zapier" but if there is a webhook you want to try, just let me know and I can enable it.

**Comment by pllim** [comment]
Closing. Feel free to reopen if needed.
