### ISSUE TITLE
Changing model parameter values and pushing update doesn't update the plot

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#141]
Couple unrelated problems, actually:

- [x] Changing model parameter values and pushing update doesn't update the plot
- [ ] Not sure the Gaussian amplitude is right on the plot...doesn't seem right.

Tried fitting a single gaussian to the region ~1-2 microns in example_spec_ascii. Initial guesses don't look crazy now. Fitting gave me
```
amplitude = 3.312e-15,
mean = 1.69,
 stddev = 1.182,
```

However the plot of the Gaussian is peaking at about 64e-15. I'm not sure that makes sense this amplitude. 

I tried changing the amplitude and stddev by hand and seeing what it looked like, but I couldn't get it to replot even pushing the update button.

**Comment by nmearl** [comment]
Checkout latest master for the first item on your list.

**Comment by nmearl** [comment]
Do any of the more recent pushes to the repository solve the issue with the Gaussian amplitude?
