### ISSUE TITLE
Trashing a model component

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#143]
Had a two-component model...highlighted the second (Const1) and pushed the trashcan item over on layer. I realize now this was wrong...that deletes the layer, not the model component....but anyway, that's what I did. What it did was remove the first component (Gaussian1) rather than the one I highlighted, or doing nothing or throwing an error. When I then went back and tried to delete the component that was left using the context menu, it crashed.

**Comment by nmearl** [comment]
Really strange. I just committed 9c7f209c0c811bd10a3317a57dcf558242f82bcc, try now.
