### ISSUE TITLE
Compound model Gaussian + linear fit doesn't do well

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#145]
Tried with L-M and Simplex and neither found a fit that looked plausible, even when I gave initial guesses that look much better. 

Spectrum is example_spec_ipac.txt. Fitting range is shown in the screenshots. Model parameters are in the .txt files attached.

[initial_val_foo.txt](https://github.com/spacetelescope/specviz/files/145431/initial_val_foo.txt)
[LM_bestfit_foo.txt](https://github.com/spacetelescope/specviz/files/145432/LM_bestfit_foo.txt)
<img width="641" alt="initial" src="https://cloud.githubusercontent.com/assets/2261329/13301519/503e80d4-db13-11e5-8202-f6b5b3a4f849.png">
<img width="644" alt="bestfit" src="https://cloud.githubusercontent.com/assets/2261329/13301521/5290676c-db13-11e5-8dfc-de56bbaf9575.png">

**Comment by nmearl** [comment]
Where is this `example_spec_ipac.txt` data set?

**Comment by hcferguson** [comment]
I had just attached it to the test-data location card https://trello.com/c/kXuhw1yl/46-test-data-location.

**Comment by hcferguson** [comment]
Tried again using roughly the same region and initial guess and SLSQP fitter and it seemed to do a few iterations and not return a better fit than my initial guess. 
```
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 6.64989904059e-27
            Iterations: 1
            Function evaluations: 7
            Gradient evaluations: 1
WARNING:root:Optimization terminated successfully.
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 4.62643436801e-27
            Iterations: 1
            Function evaluations: 7
            Gradient evaluations: 1
WARNING:root:Optimization terminated successfully.
```

**Comment by hcferguson** [comment]
I suggest taking this spectrum and this region and maybe a few other examples and trying to do the fitting by hand outside of specviz to see what kinds of parameter tweaking and initialization will be robust for the common use case of "fit a gaussian emission line on top of a sloping continuum."

**Comment by ibusko** [comment]
If this use case is common enough, we could create our own "Gaussian + linear" model, and put it in the model drop down list. The same with other popular use cases. That way, we could have custom initializers that might be able to do a better job than when we add together otherwise loosely-connected models from astropy.

**Comment by pllim** [comment]
:+1: to custom recurring composite models, or even subclass if it is not composite but just a bit non-standard.

**Comment by ibusko** [comment]
Using the area under the Gaussian to estimate its amplitude only works if the continuum is first subtracted. This is what is causing the initialization here to go bonkers. Having a Gauss+Linear model would automatically include that subtraction. In cases like this example, using the older amplitude initialization (max - min of the flux data) with the current models would be more robust.

**Comment by ibusko** [comment]
This is what I got after tweaking the amplitude and fwhm by hand, and running L-M 4X in succession:



![untitled](https://cloud.githubusercontent.com/assets/3577145/13397359/97c7f6bc-dec7-11e5-9925-0bcd0f58ac86.jpg)

**Comment by ibusko** [comment]
So, just to re-iterate what we discussed yesterday (2/16/2017) at the tag-up, I understand I should go ahead and implement a Gaussian+linear model in the repertoire of available functions.

**Comment by hcferguson** [comment]
I would rather see a more general solution to the problem with the fitters converging too soon, but I agree that having this as a canned composite model might be handy. Digging into the underlying problem of the fitters converging on bad fits seems like a higher priority.

**Comment by ibusko** [comment]
Here is what I found so far:

By definition, the fitters don't return anything that would tell that they got stuck in a secondary minimum. I did run some tests to confirm that, and to visualize their behavior in more detail. I dump the fitter internal state variables at the point they stop iterating, and start a new run from that point. Keep repeating this a few times. I look for patterns in the internal state. I see nothing that tells that any particular minimum is not the best. The behavior is dependent on the fitter's initial and control parameters, such as tolerance and step.  Besides, each particular algorithm has a different set of state variables, which would make difficult, if not impossible, to come up with some generic criterion for detecting non-optimal fits.

A possible solution to this conundrum  would be to wrap the fitter call in a loop that would call the fitter repeatedly (simulating multiple hits of the "Perform fit" button, but all in a single thread), and would compare the progression of each parameter value towards convergency. This kind of solution would have to deal with situations where one or more parameters never really converge, but keep instead jumping back and forth between two close values. In any case, it would be a rather complex solution that, even if it works, would probably fail in some unforeseen cases.

I any case, we should update the documentation to alert users of those behaviors and suggest that it's good practice to hit the "Perform fit" button more than once.

**Comment by ibusko** [comment]
After the tagup today, where Nick rightly pointed out that the problem can be highly relieved by the careful choice of ROI, initial parameter values, and control parameters, it came to mind that what is lacking in fact is a report of goodness-of-fit. Maybe just a chi-sq-like scalar reported somewhere in the model fitting window would suffice as a first shot at that. A plot of the residuals would also go a great distance in giving the user confidence in the results.

**Comment by hcferguson** [comment]
I think it might be helpful to take one or two datasets of "gaussian + linear" and fit them without using Astropy to see if the default behavior of other packages is better.  If there is something wonky about the Astropy optimizers then we might be barking up the wrong tree in looking at solutions like "improve the initial guess" or "perturb the guess and refit." 

There is an example  of fitting a Gaussian (without the linear part, so maybe start with that?) at http://python4esac.github.io/fitting/examples1d.html using scipy curve_fit. Another example using lmfit at https://lmfit.github.io/lmfit-py/model.html.  Another using leastsq at https://github.com/tiagopereira/python_tips/wiki/Scipy:-curve-fitting. Another using np.linalg.leastsq at http://central.scipy.org/item/28/2/fitting-a-gaussian-to-noisy-data-points. 

There is a 2D example using mpfit from Adam Ginsburg at http://www.adamgginsburg.com/pygaussfit.htm .

**Comment by ibusko** [comment]
I added examples of some of those fitters, including the astropy ones as they are used in specviz, in the notebook here:  https://github.com/ibusko/experiments_specviz/blob/master/experiment_1.ipynb

The data in the notebook is the same as used in the example on this issue (example_spec_ipac.txt).

I worked first on the easiest (meaning, quickest) to implement: astropy (the three fitters), curve_fit, and lmfit. The ODRPACK code requires computation of derivatives of the Gaussian+Linear function so it will take longer for me to get it right (needs more testing). The SciPy Central doesn't look to be usable with Gauss+linear without significant modification and experimentation. Again, will take awhile. Same for the 2D code. 

So maybe we should prioritize what to do for this sprint. I suggest the ODR as best next step so we will have a chance of having something by the end of the week.

**Comment by ibusko** [comment]
Please disregard the notebook pointed above. Use this instead:

https://github.com/ibusko/experiments_specviz/blob/master/experiment_2.ipynb

**Comment by ibusko** [comment]
I drilled down a little more on the fitters offered in spicy.optimize. The code is in notebook https://github.com/ibusko/experiments_specviz/blob/master/curve_fit.ipynb

I wrote down some of my findings in comments in that script. Here I copied and pasted the comments so they are easily accessible: 

 'scipy.optimize.curve_fit' is mostly a convenience wrapper around two functions, 'scipy.optimize.leastsq' and 'scipy.optimize.least_squares'. 'leastsq' is in turn a wrapper around MINPACK’s lmdif and lmder algorithms. These are implementations of the L-M algorithm. Which one gets called depends on the user providing a callable to compute the Jacobian. If not provided, it's estimated. 

 astropy's LevMarLSQFitter is basically a wrapper around 'leastsq' as well. The add-on factor is that it handles the constraints and ties that are an integral part os astropy's fitting mechanism, but are not recognized by the scipy routines. Thus there is no point in attempting to add 'curve_fit' (with  the default 'lm' method) or 'leastsq' to specviz's fitters drop-down menu. The functionality is already all there.

Calling 'curve_fit' with initial guesses for the parameters does not work  regardless of the combination of first guesses and  methods used. These calls either raise an exception when reaching maxfev, or just skip everything and return the first guesses as the answer. 

'scipy.optimize.least_squares' gives access to three different optimizers: 'lm', 'trf', and 'dogbox'. With 'lm' it defaults to calling 'leastsq'. Any benefit provided by including 'least_squares' in specviz would come then from its ability to run the 'trf' and 'dogbox' algorithms.  Both 'trf' and 'dogbox' are the only algorithms in scipy capable of handling bounds. These might be of interest in the future; here, we run some experiments with bounds. Note that, to add 'least_squares' to specviz's code, it should be re-cast into the astropy Fitter meta class framework, and implement code that handles constraints and ties (a non-trivial task).
 
'least_squares' provides a rich set of input parameters to control and monitor the fitting process. These abilities are probably beyond the scope of specviz.

**Comment by kassin** [comment]
Ivo, this is super.  What are people's thoughts on including Ivo's descriptions in the documentation?  I think they'd make great crib notes for the fitters... and will save lots of people's time digging through astropy documentation (and code) to figure out what's behind each fitter.  I know documentation like this is somewhat redundant, but still very useful.

**Comment by ibusko** [comment]
Tests of ODR are also in https://github.com/ibusko/experiments_specviz/blob/master/curve_fit.ipynb

**Comment by hcferguson** [comment]
Closing this. The issues with fitting not working were largely addressed by the @ibusko modifications to the pre-refactor Specviz to make good first guesses at the parameters. Since the fitting has moved to SpecUtils, that first-guess code needs to get in there too (issue [201](https://github.com/astropy/specutils/issues/201)).

**Comment by brechmos-stsci** [comment]
@hcferguson Parameter estimation was added in PR https://github.com/astropy/specutils/pull/362
