### ISSUE TITLE
Display region bounds

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#147]
There's no way to know explicitly the wavelength ranges of the region selections. Should these be displayed in the plot window? Should they only be extracted when the data is exported?

**Comment by hcferguson** [comment]
If they fit, it would be useful information. I can imagine several approaches:

- show the range when adjusting but make it disappear to avoid clutter
- show the range when the region is selected but make it disappear to avoid clutter
- show the range when the mouse hovers

In all of the above, there is on way for the user to cut & paste values. Also, they don't see the ranges of all the ROI's, just one at a time.

- Provide a "verbose" version of the stats and measurements that will print out all the values as well as the ranges in a popup text window.
- Provide a "save" version of the stats and measurements that will format this same information to a YAML file and save it on disk.

**Comment by hcferguson** [comment]
Region bounds are now shown in the stats window.
