### ISSUE TITLE
Linear model initialization

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#148]
I don't think the `_Linear1DInitializer` is going to be a good general algorithm for initializing. I've attached one example where it goes bonkers. I would suggest just setting the slope to 0 and using the intercept as the `AMPLITUDE` from the `_WideBand1DInitializer`. 
<img width="644" alt="screen shot 2016-02-24 at 9 33 21 pm" src="https://cloud.githubusercontent.com/assets/2261329/13308288/0378bc9c-db40-11e5-8048-6fbbdd467f44.png">

**Comment by hcferguson** [comment]
Incidentally, notice also the behavior that the model layer is making half the plot, even outside the RIO, have a much higher line. That seems to happen a lot. Makes it a bit hard to see the line on a retina display.

**Comment by ibusko** [comment]
Just pushed new initializer for the linear model.

**Comment by pllim** [comment]
Closing. Feel free to reopen if needed.
