### ISSUE TITLE
Implement logging

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#15]
Populate functions with relevant logging, allow user to access logs through either gui or command like (through the `pyfocal` entry point?)

**Comment by pllim** [comment]
Given that eventually this package is going to be Astropy affiliated (see #40), it is easiest to use the logging functionally that comes with Astropy, as documented in http://astropy.readthedocs.org/en/latest/logging.html .

**Comment by nmearl** [comment]
This is essentially implemented. We've decided against using Astropy's logging for now.
