### ISSUE TITLE
Mask default values in loader

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#153]
Question for @nmearl -- From what I understand thus far, if mask is not supplied by user, mask should be set to all ones to select the entire spectrum, right? But in `interfaces/loaders.py`, the mask is always set to zeroes by default (even as far back as c9655c44a2c5f0b7fbcfecdb51095f564afe44eb). I am confused.

**Comment by nmearl** [comment]
NDData objects use the [definition](http://docs.astropy.org/en/stable/nddata/#getting-started):

> A mask value of True indicates a value that should be ignored, while a mask value of False indicates a valid value.

But the `_mask` attribute of `Layer` objects use the opposite.

**Comment by pllim** [comment]
So, where does the value flipping happen in the codes?

**Comment by nmearl** [comment]
To my knowledge, currently, the `mask` inside the `NDData` object is not used anywhere (that is, we don't mask any of the raw data based on e.g. dq flags or something). This begs the question of how persistent that mask should be.

1. Should the `NDData` mask be applied all the time? (But then we're missing data in all subsequent layers).
2. Should the `NDData` mask act as another plot? (Like the previous SpecView project, I had the mask displayed as red circles on the plot, but all of the data was used in other parts of the application).
3. Should there be a flag in the `Data`/`Layer` object that states when the mask should be applied? E.g. (pseudo code):
```python
class Layer(object):
    ...
    @property
    def data(self):
        return self._source[~self._source.mask][self._mask]
```

**Comment by pllim** [comment]
Okay, I think I need to fix loader to treat mask correctly then based on your other reply. As for mask usage, it is somehow used during fitting -- see #150.
