### ISSUE TITLE
YAML format for  model files.

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/specviz#154]
I have a new module that implements reading and writing models from/to files in YAML format. It uses yam.safe_load to minimize the security issue. The module that implements the same functionality but using .py files is still present. Right now, we select which one to use by changing an import statement in controller.py.

This raises a number of issues:

- we can do the replacement right now, but that will leave not much time for testing. Also, my code as of today cannot use the arithmetic expression in the UI. When reading from the YAML file,  it always builds a compound model by adding together the models in the file. Which is probably the most common use case, but a limitation nevertheless, that I will start addressing next.

- we can leave the code as is. Pushing the new module in the repo doesn't affect the code that actually runs because this new module is never imported. This would be just for safekeeping of the new code.

- we can leave the code as is and hide the Load button in the UI to prevent users of this first release to ingest .py files. In fact, main main goal with the .py files is to enable users to export their compound models in a form that they can readily use in their analysis scripts elsewhere. 

My proposal for a future release would be to keep both the Save and Load buttons connected to the YAML module so users will be able to propagate their models in between specviz sessions. And, we would add a new Export button that would write models to .py files, in the same way the Save button works now.

What do you think?

**Comment by hcferguson** [comment]
Seems like the third option makes the most sense for this release.

**Comment by pllim** [comment]
:+1: to adding the module in repo anyway for version tracking, even if it is not used.

**Comment by ibusko** [comment]
Closing based on discussion at last tag-up.
