### ISSUE TITLE
Centroid needs to be paired with EW measurements

### ISSUE THREAD

**Issue by gderosa2004** [spacetelescope/specviz#155]
As is, we are measuring the centroid of a region, while we are interested in the centroid of the emission/absorption line (continuum subtracted). My suggestion is to use one button and do both measurements at once. Measured quantities that we should output: a) centroid, b) EW, 4) cont flux at the centroid, 5) line flux

**Comment by gderosa2004** [comment]
We also need more significant figures in the centroid output

**Comment by nmearl** [comment]
So, you're proposing that when a user clicks on the Equivalent Width button that the central region be used to also calculate the centroid? Are you suggesting that the other two outer regions be used to calculate the continuum and then use that to subtract from the centroid?

**Comment by gderosa2004** [comment]
I'm suggesting that we estimate the centroid of the continuum subtracted region. Does it make sense?

**Comment by nmearl** [comment]
Right, yeah, that makes sense. But, you're suggesting a workflow like:

1. Go into "Equivalent Width" mode where the three regions appear on the plot.
2. Move the two outer ones to the continuum you want to measure.
3. Move the center one to the line of interest.
4. The equivalent with will update by passing all three regions to the statistics module.
5. The centroid will update by
  1. Getting the data of the middle selection region,
  2. Getting the value of the continuum,
  3. Subtracting the continuum from the data in the selection region,
  4. Passing this resulting data to the `centroid` function to calculate the centroid.

**Comment by gderosa2004** [comment]
So in eq_width I'd call centroid(data) where data=line.dispersion,line.data-avg_cont

**Comment by gderosa2004** [comment]
yep, I think we're saying the same thing :-)

**Comment by nmearl** [comment]
Done in 4accb72c3454565111a08088e100f23de72ca5d5.
