### ISSUE TITLE
Un-toggle a mode automatically when another mode is toggled

### ISSUE THREAD

**Issue by gderosa2004** [spacetelescope/specviz#156]
I ALWAYS forget to untoggle the EW mode and have a few sec of craziness..

**Comment by nmearl** [comment]
Don't you also want to unify the centroid and EW modes as described in #155?

**Comment by gderosa2004** [comment]
Yes.. It was more a general request :-)
We’re gonne put there more options in the end I imagine..

**Comment by nmearl** [comment]
We'll keep this in mind going forward.
