### ISSUE TITLE
HST/COS YAML file doesn't work on other COS spectra

### ISSUE THREAD

**Issue by gderosa2004** [spacetelescope/specviz#158]
I got the following error while trying to upload another cos spectrum (not in the test folder). Looking in the yaml file.

```
Traceback (most recent call last):
  File "/Users/gderosa/anaconda/envs/sviz_env/lib/python3.5/site-packages/pyqtgraph/graphicsItems/ErrorBarItem.py", line 146, in boundingRect
    self.drawPath()
  File "/Users/gderosa/anaconda/envs/sviz_env/lib/python3.5/site-packages/pyqtgraph/graphicsItems/ErrorBarItem.py", line 71, in drawPath
    y1 = y - height/2.
ValueError: operands could not be broadcast together with shapes (2,) (2,16384)
Abort trap: 6
```

**Comment by pllim** [comment]
I find that the loader + YAML is very sensitive to data format. So, if the format is slightly different from the COS data file you provided for testing (which was the one I used to build the YAML), then you will need a custom YAML.

**Comment by pllim** [comment]
@gderosa2004 , did you find a solution for your COS file? Can I close this issue?

**Comment by pllim** [comment]
Closing. Feel free to reopen if needed.

**Comment by gderosa2004** [comment]
Sorry, I didn't have any time to look into ANYTHING - I have 2 deadlines by the end of this week. Next week I'll be able to do some work on it.
