### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#16]
Extend the `pyfocal` console script to allow command line arguments:
- arg: passing fits file from command line
- kwarg: getting pyfocal version

etc.

**Comment by ibusko** [comment]
To a developer, it's nice to be able to pass the input file name via command-line. It saves quite a bit of interaction when cycling thru a edit-build-run loop over and over. Any chance we can bump up the priority for this? I volunteer to do it when I finish the model fitting basic implementation.

I actually had it done in the old specview already.

**Comment by nmearl** [comment]
Sure thing, if you'd like to take a crack at it. I agree that it's very useful.

**Comment by pllim** [comment]
Do you plan to support wildcard, like `pyfocal *.fits`?

**Comment by ibusko** [comment]
My plan is to have a bare-bones implementation that I can put together in a couple hours so as to facilitate my development workflow. I am not concerned with wildcards at this point. But it could be put in at some future release, I am sure.

**Comment by ibusko** [comment]
I committed a simple code change that enables reading a FITS file when the file name with full path is present as first argument in the command line. I tested this with just the generic_spectra.fits file. 

I assume we are not going to advertise this in the public release, at least not before adding more capabilities (such as reading any of the supported file types) and adding checks to catch user errors.

**Comment by pllim** [comment]
I added support for loading ASCII too from command line in #51. Still no wildcard support, but I think we can advertise it as "use only if you know what you are doing" if we wish.

**Comment by eteq** [comment]
From #101 which I created without realizing this exists:

I was surprised to find that ``pyfocal --help`` crashes because it thinks ``--help`` is a file I'm asking for.  I suggest using [argparse](https://docs.python.org/3/library/argparse.html) in `App.__init__` or even `main` to do the command-line parsing.  That way a user will see a more traditional and familiar command-line interface, and will make it easier to start adding command-line switches down the road.

**Comment by hcferguson** [comment]
Status as of 12/19: 
 
-  -- help works
-   -L isn't particularly useful without a list of loader names
- Fails to recognize .ecsv and just use that loader (e.g.)
