### ISSUE TITLE
Mask handling in layers

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#161]
As mentioned by @nmearl in #153, and repeated below:

To my knowledge, currently, the mask inside the `NDData` object is not used anywhere (that is, we don't mask any of the raw data based on e.g. dq flags or something). This begs the question of how persistent that mask should be.
1. Should the `NDData` mask be applied all the time? (But then we're missing data in all subsequent layers).
2. Should the `NDData` mask act as another plot? (Like the previous SpecView project, I had the mask displayed as red circles on the plot, but all of the data was used in other parts of the application).
3. Should there be a flag in the `Data`/`Layer` object that states when the mask should be applied? E.g. (pseudo code):

``` python
class Layer(object):
    ...
    @property
    def data(self):
        return self._source[~self._source.mask][self._mask]
```

c/c @ibusko , @hcferguson , @kassin, @gderosa2004

**Comment by ibusko** [comment]
Yesterday, when playing with the fitting tool using short-spanned wavelength regions, it occurred to me that sometimes it would be useful to see the fitted model plotted over the entire data range, even though it was fitted only over a small portion of the data. In those cases, having the ability to make the plot routine ignore the ROI would be useful.

**Comment by nmearl** [comment]
Actually, there is something like that already. When you're on the model layer, if you change the size of the ROI and click "update", it will use your current model and the new region. You can make this region the size of the plot to see the model that you fit to just a small part be applied to the entire thing.

**Comment by nmearl** [comment]
<img width="1392" alt="screen shot 2016-02-26 at 9 39 38 am" src="https://cloud.githubusercontent.com/assets/4141126/13355146/e7086d04-dc6c-11e5-9438-01e67431295b.png">
<img width="1392" alt="screen shot 2016-02-26 at 9 39 46 am" src="https://cloud.githubusercontent.com/assets/4141126/13355142/e540acd4-dc6c-11e5-9058-22e634c4e06d.png">

**Comment by ibusko** [comment]
Ahh.....that's very useful. Maybe I should read the docs before complaining about something :-)

**Comment by pllim** [comment]
I don't think it is in the docs but probably should be.

**Comment by nmearl** [comment]
Behavior has been changed to fitting over the current ROI region if any ROIs exist, otherwise, fitting over the entire spectrum. Likewise, the generated model is always the same shape as the data in order to facilitate layer arithmetic.
