### ISSUE TITLE
Arithmetic behavior crashes

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/specviz#163]
I traced the problem down to the get_model_inputs in the Viewer class. The model instances it retrieves from the Qt objects stored in the GUI tree have their 'name' attribute set to None. This causes the Parser to choke because it can't match model names with whatever is typed in the arithmetic formula.

Now, I don't know if the model names should be carried inside the model instances themselves, or should be built on the fly by get_model_inputs itself, since they can be re-defined by the user by typing on the tree. @nmearl , you probably have the answer to this?

**Comment by nmearl** [comment]
Try with the latest master.

**Comment by ibusko** [comment]
Fixed ! Thanks, I am closing this issue.
