### ISSUE TITLE
EW and line flux attributes swapped

### ISSUE THREAD

**Issue by gderosa2004** [spacetelescope/specviz#164]
I've just tested the updated version, and in the measured windiw the EW is displaying the line flux (And vice versa)
![screen shot 2016-02-26 at 10 41 07 am](https://cloud.githubusercontent.com/assets/15363065/13356852/80880518-dc75-11e5-971a-05c145eba178.png)

**Comment by nmearl** [comment]
Try now with the latest commit f29902f8aa0c0725144596c8d67d2c0ffcea4500.

**Comment by gderosa2004** [comment]
Yep. Problem solved!
