### ISSUE TITLE
Data point count does not make sense

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#168]
When I load a data file (again, Gisella's MDM test data), under statistics box, the "data point count" is reported as 1, although the stats are supposed to be calculated from the entire spectrum. See screenshot below:

![untitled](https://cloud.githubusercontent.com/assets/2090236/13365697/99de4f20-dca4-11e5-9d8d-0f9564195e60.png)

**Comment by nmearl** [comment]
Should be fine now.

**Comment by pllim** [comment]
:+1:
