### ISSUE TITLE
Model name is not stored in the model instance?

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/specviz#169]
This is for @nmearl - when we change the name of a model by typing the name on the list in the GUI, the name attribute of the underlying model instance does not change. I am detecting this by tracing thru the get_model_inputs method in the Viewer.

This prevents the model name to make to the output file. get_model_inputs always returns with the original model names in the instances. Then, if we read the file back, and there is a arithmetic expression in the model, it crashes.

**Comment by nmearl** [comment]
Yes, it was designed so that changes weren't "flushed" to the model objects until you hit "Update Layer". I've changed it so that flushing changes occurs at every interaction with the gui objects. Try now.

**Comment by ibusko** [comment]
Works great! Thanks!
