### ISSUE TITLE
astropy.modeling.models has no Planck function

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/specviz#170]
That seems to me a pretty basic model for spectra fitting. Should we formally post a request in astropy? Or develop our own?

**Comment by pllim** [comment]
There is one. I added it to `astropy`. It just is not in `modeling` because that function is highly depended on units and `modeling` cannot handle `Quantity` yet. See http://docs.astropy.org/en/stable/analytic_functions/index.html#using-astropy-analytic-functions

I hacked together a `Blackbody` model for `pysynphot` a while back but that project is on hold.

**Comment by ibusko** [comment]
So, should we add it to specviz's list? Or the units dependency may create new issues that we won't be able to deal before the release?

**Comment by pllim** [comment]
Look at https://github.com/spacetelescope/pysynphot_DONOTUSE/blob/master/synphot/models.py#L30 and tell me what you think...

**Comment by ibusko** [comment]
The blackbody_lambda and blackbody_nu models are in fact functions, as suggested by the example. Is that right?  If so, in order to be usable in specviz, they should instead subclass Fittable1DModel  In that case, they can be used as the core of a model class that we will have to develop ourselves.

**Comment by nmearl** [comment]
A [basic custom one](http://docs.astropy.org/en/stable/modeling/new.html) should be straightforward

```python
from astropy.modeling.models import custom_model
from astropy.units import Quantity

@custom_model
def blackbody(wavelength, temperature):
    wavelength = Quantity(wavelength, "Angstrom")
    temperature = Quantity(temperature, "K")
    return blackbody_lambda(wavelength, temperature).value
```

**Comment by pllim** [comment]
If you can make it work, go for it. The only thing that stopped me was lack of unit support in `modeling` machinery. And as I understood from astropy/astropy#4615, the fitting itself would not support units internally. So, whatever you put together now will break when that PR is merged.

**Comment by ibusko** [comment]
Implemented Blackbody model. Hence, this ticket can be closed.

**Comment by cheekujodhpur** [comment]
@ibusko Where is this model implemented? I do not see it in the latest code. 

What am I doing wrong?
