### ISSUE TITLE
Mysterious icons need tooltip

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#171]
![screenshot](https://cloud.githubusercontent.com/assets/2090236/13400329/392ca072-ded5-11e5-87c1-33195612917d.png)

I don't know why there is a big floppy disk button and a small one, each on a side of the folder icon.

**Comment by nmearl** [comment]
While I'm the that consolidated the display into those consistent buttons, I'm not sure what that second save button is. @ibusko did you add that?

**Comment by ibusko** [comment]
The folder icon is for the Load model (from YAML file) functionality. The small floppy is for the Export (to .py file) functionality. I added these as per discussion during the last tag-up. I couldn't find a better icon for the Export button; please feel free to change them as you see fit. I think I added tool tips for them though.

**Comment by pllim** [comment]
If you added tooltip, they are not displaying on Anaconda/Qt4/RHEL6.

**Comment by nmearl** [comment]
@pllim are you seeing any tooltips? E.g. even the one on the buttons in the data and layer docks?

**Comment by pllim** [comment]
Nope. I hovered for maybe 1-2 secs. How long am I supposed to hover for it to appear?

**Comment by pllim** [comment]
Tooltip works now. Thanks! Also the new icon is less confusing.
