### ISSUE TITLE
Layers cannot handle two simultaneous files

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#174]
I have slice and model layers for one image active. Then I open a second image (new sub-window). I try to recreate same slice and model, but for the second file. I get the following traceback (no crashing but things not working properly):

``` python
ERROR:root:Traceback (most recent call last):
  File ".../specviz/core/comms.py", line 112, in wrapper
    return func(*args, **kwargs)
  File ".../specviz/ui/controller.py", line 520, in _update_layer_name
    layer = layer_item.data(0, Qt.UserRole)
RuntimeError: wrapped C/C++ object of type QTreeWidgetItem has been deleted
```

p.s. Can't remember if someone else reported this before or not. Sorry if this is a duplicate.

**Comment by nmearl** [comment]
I tried to emulate:

1. Load data
2. Create sub window
3. Add an ROI and create a slice (now I have two layers)
4. Create another sub window
5. Add an ROI and create a slice (now I have two layers on the new sub window).

I do not see an error -- is this what you are doing?

**Comment by pllim** [comment]
1. Open `n5548_120201` (MDM).
2. Create a layer slice with ROI tool.
3. Add Gaussian and Const models to the layer slice. Click "Create Layer".
4. Open a second file `n5548_120202` (also MDM) that creates a new sub-window.
5. Repeat Steps 2 and 3 with this new sub-window.

**Comment by nmearl** [comment]
With the GUI changes and the re-implementation of layer interaction behaviors, this no longer seems an issue. Please re-open if you still experience it.
