### ISSUE TITLE
Statistics confusing when ROI is active

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#177]
I was confused why statistics values were not changing when I switch layers. Then I found out they only change properly when I deleted the ROI (with context menu). Otherwise, statistics always report from data within the ROI, no matter which layer I am on. I can't tell whether this is a desired feature or not.

**Comment by nmearl** [comment]
I do not see this. If I have multiple layers (e.g. a model layer) and there is an ROI on my plot, clicking back and forth changes my statistics values.

Can you be more specific about your workflow?

**Comment by pllim** [comment]
1. Open n5548_120201 (MDM).
2. Create a layer slice with ROI tool.
3. Add Gaussian and Const models to the layer slice. Click "Create Layer".
4. Now toggle between the three layers and look at Basic statistics.

**Comment by nmearl** [comment]
When I follow those instructions, the basic statistics will update when I move to or from the Model Layer. However, if I do not move the ROI, then I expect that the Layer and Layer slice should give the same statistics. They both contain the exact same data (if you don't move the ROI).

**Comment by pllim** [comment]
Yeah, I didn't move the ROI. It's just confusing because the data is highlighted differently when I toggle between layers. But the current behavior makes sense once documented.
