### ISSUE TITLE
Model data not respected with arithmetic

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#179]
The arithmetic looks at the parent `NDData` object of the `Layer` to do the arithmetic (because that's where the `NDArithmeticMixin` is implemented).

Need to create a new `NDData` object with the model data when doing arithmetic with models.

**Comment by pllim** [comment]
I am setting this milestone for the next sprint. But feel free to change if you think otherwise.

**Comment by nmearl** [comment]
Fixed in the latest version.
