### ISSUE TITLE
Make (option for?) "Update Layer" to happen automatically

### ISSUE THREAD

**Issue by eteq** [spacetelescope/specviz#181]
When manually fiddling around with model parameters, I find it a bit awkward to have to click the "Update Layer" button every time I change a parameter value.  Might it be possible to instead have the update happen automatically if the parameters get changed?  Or perhaps there should be a check-box next to "Update Layer" to toggle auto-updating on or off?

This might be less important if #130 goes in to make the clicking less of a scroll down, but it still would be nice as an option.

**Comment by pllim** [comment]
This needs to be approached carefully. What if I want to change both "mean" and "std" to get the Gaussian right, but Gaussian auto-update after I only entered the correct "mean" and I see a bunch of unintended consequences?

**Comment by eteq** [comment]
@pllim - In practice I think this is fine because if the user updates mean and sees some other stuff change, they'll know very well that they need to update std before it makes any sense - after all, they *actively* chose to manually edit the parameters.

(If it wasn't clear, BTW, I am *not* suggesting to auto-fit - there it definitely doesn't make sense due to the non-linear nature of some of the fitters.  This issue is about auto-updating the plot based on the parameters as manually entered)

But I certainly see your point that this could still have unintended subtle consequences.  So that's why I was thinking a check-box would be suitable.  Probably default it on, but if the user gets confused by this they can always turn it off.

**Comment by pllim** [comment]
By the way, I think this had been brought up before in one of the sprint tag ups and @nmearl responded there but I don't remember exactly what the response was...

**Comment by nmearl** [comment]
Changed in latest version: models are updated as parameters change.
