### ISSUE TITLE
Expose advanced parameters for fitters

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#184]
As discussed in #182, expose these under "advanced" section under Model Fitting:
- [x] `maxiter`
- [x] `acc`
- [x] `epsilon` (optional)

**Comment by ibusko** [comment]
Is the "advanced" section already in there somewhere? I can't see it. Should it be a tab in the model window?

**Comment by ibusko** [comment]
Note that epsilon is fitter-dependent. For instance, astropy's simplex crashes with

TypeError: fmin() got an unexpected keyword argument 'epsilon'

when blindly called with the keyword. The code in specviz should somehow know of these fitter-dependent issues.

**Comment by nmearl** [comment]
The way I've implemented it is that there are the three keywords exposed above in the GUI, however, the logic will run a `hasattr` on the fitter instance before attempting to call it with the keywords. This avoids crashing, but also means the user might not be aware that some of the keywords are not being used.

Alternatively, we could have the advanced parameters provide fitter-dependent fields, but that would require we know which fitters we're providing. ;)
