### ISSUE TITLE
Important questions for current users of NDData

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#197]
This was brought up by Perry in Astropy dev mailing list (`astropy-dev` Google Group). I remember seeing extensive use of these features here. Please tell him how you feel about this in the mailing list.

<hr/>

There was a recent meeting with LSST developers right after the last Python in Astronomy workshop, held at the University of Washington at the end of March. There is serious interest by LSST in making their software more compatible with Astropy. One of the specific issues raised by them were changes they felt were needed so that they could provide their data in a form compatible with NDData. A number of these changes would likely involve changes to the existing interface of NDData. We are not entirely clear how many users would be impacted by these changes, and how much work this would imply for these users in order to incorporate these changes. Hence this at surveying the existing users.

Issues like this are a difficult balancing act between the pain caused by making backward incompatible changes and the significant advantages of exposing LSST data analysis tools to the general astropy community. Thus it is important for the astropy coordinators to have a good read on the impact of the changes. To keep this from getting very long, we won’t go into great length as to justifying the LSST requests other than to say there are good reasons to consider them.

The requested changes fell into different categories, and we wish to understand the impact of these changes by category rather than as a whole so that decisions can be considered at a finer level rather than “no changes” or “all changes”. If you use NDData in your software, please give us a response as to the consequences of these changes. If others use your software, also give us an idea of the number of users of your software.

Thanks, Perry Greenfield

Question 1: Partitioning of NDData attributes and behaviors.

This is the most complex issue and will take a little space to describe. LSST would like something simpler than NDData for which array operations are straightforward. For example, being able to add, subtract, and multiply arrays without worrying about how to deal with other complexities such as how to combine the metadata or deal with the WCS. They would also like to do simple slicing on such arrays (while also retaining information about the new array’s origin relative to the parent array).
This requires disassociating some things we have originally bound to NDData such as .wcs or .meta (though we probably could keep units since all such operations have generally a very clear interpretation).

Instead, they prefer that information to be included with a higher level object. For example, if NDData remains the simpler object (these names would have to be argued about; what is mentioned here is simply for discussion purposes), then there would be a higher-level object; here we will call it NDObs. How this higher level object would work is still not entirely clear. LSST prefers to have some standard attributes such as exposure time and and filters split out from meta. Others feel that this can vary quite a bit from one area to another and prefer to keep these in meta. From a backward compatibility viewpoint, this is not really relevant since something is going to work differently. There is also discussion as to whether NDObs would be a subclass of NDData or that it would have an attribute that contains an NDData instance (the argument [strong in my view] is that subclassing is dubious when you disable much of what can be done in the parent class, such as arithmetic operations or slicing).

To summarize: moving things like meta, wcs from NDData to NDObs which encompasses NDData in some manner.

Although this breaks the current NDData mixin tools (e.g., NDArithmeticMixin), nothing prevents the same sort of mixins from being used for NDObs (and it isn’t needed for NDData since that capability is built in).

In some cases, users of NDData mainly only have to change the name of the instantiating object, but in others attribute access and methods may change. It all depends on the final details.

Question 2: Interface to data masks.

Currently NDData has an optional .mask attribute that is expected to behave as a boolean array. LSST (as well as other organizations, such as STScI) require masks with multiple bit planes and the capability to generate boolean masks in flexible ways from the bit planes. One may be able to preserve the existing interface while making .mask a property generated from internal representations, and using methods to set how the boolean mask is to be generated. LSST is suggesting that mask itself be a more complex bitplane mask with extra methods (presumably requiring a subclass of numpy arrays) to generate a boolean array, or expressly using boolean operations to select the bitplanes of interest. Even though a non-boolean integer bitplane array can be used as boolean, but not being expressly boolean means it is interpreted differently by numpy (e.g., as an array index). As I read it, the current documentation is unclear as to the required type of the mask array.

The LSST proposal would have ndd.mask.bool() return a boolean array, where .bool() could take optional arguments to indicate which bitplanes of the mask to use in deriving the boolean result (e.g., ndd.mask.bool(‘bad’,’saturated’) ). The other option is that ndd.mask is always boolean and one changes how it is generated by doing things like ndd.set_mask_planes(…), ndd.get_mask_plane_keys() (names here are only suggestive, nothing has been proposed as far as names go).

Since subclassing numpy arrays in the first case above tends to introduce a lot of messy issues, it suggests the real choice is whether we want the interface to mask to be: ndd.mask or ndd.mask.bool() (or something similar). The later compartmentalizes masks issues more cleanly (i.e., we don’t litter the NDData namespace with a potentially growing number of attributes and methods, but it does definitely break backward compatibility.

Question 3: Interface to uncertainty information

Given the looseness of the current definition (from the docs: "uncertainty : any type, optional Uncertainty on the data. The uncertainty must have a string attribute named uncertainty_type, but there is otherwise no restriction.") it almost invites incompatible uses of it. But it still would be good to know who is using it and how. Some have interpreted this as standard deviation, some as variance. Is there consensus for settling on one one? Usually any propagation of this is done assuming that it is gaussian, though there are many different approaches for dealing with uncertainty that automatic propagation appears unwise (use of a mixin could allow that). Other uses entail multiple uncertainty components (e.g., random vs systematic, covariance information, etc.). Should this attribute be kept simple?

**Comment by hcferguson** [comment]
@pllim @perrygreenfield @eteq @nmearl What's the status here? I'd just as soon close this issue for SpecViz even if it's an open issue elsewhere.

**Comment by perrygreenfield** [comment]
I'm not up on the very latest. Some progress has been made, mostly by Matt Craig I  believe, but there is still work to be done. Personally, I think LSST should take on some of this work despite their claims of not being able to commit resources to this sort of thing. They haven't been clamoring much lately so it doesn't seem that urgent (from what I saw at the Astropy Coordination Meeting).

**Comment by pllim** [comment]
cc @mwcraig since he was mentioned above.

I don't have much to add here, as I don't remember posting this from 2 years ago. 😅

**Comment by mwcraig** [comment]
I think you can close this -- the changes to NDData envisaged at this point are much narrower in scope than was originally contemplated, largely for the reasons Perry outlined.
