### ISSUE TITLE
User feedback on v0.1.2rc3

### ISSUE THREAD

**Issue by josePhoenix** [spacetelescope/specviz#199]
I'm sure nobody wants UI/UX design feedback on a release candidate, but here are my thoughts :)

As far as the practical matter of installing with Astroconda, that went without incident. I'm not sure if there should be a real dock icon on the mac, but I don't get one. (Not even the Python launcher 'rocket' icon.) I get a white sheet of paper with the 'alias' arrow overlay. (It starts fine though.)

Here are my impressions from trying to load an example dataset (from @nmearl) and fit a model to it. Delivered as a sort of stream of consciousness...

## On first start

  * Why is the "Open" button the only menu button?
  * It looks like "Open" is only to open datasets. Maybe put the "Open" button in the "Data" pane to reinforce the conceptual connection. Also: this would save vertical space on small screens.
    * Shading the background of the data list view and overlaying a 'Click here to open a thing' button would make for a clear first action / guided tour aspect. Until at least one dataset is loaded, there's only one thing to do with the tool, so it should be made obvious. (Unless people are expected to invoke it from the command line, like ds9? But still.)

## After opening a data set

  * I navigated to the folder where the sample FITS data set lives, and it was grayed out. I had to go and select "*.fits", which seems silly. The default should be "all supported data types" (or "fits", if we're being conservative). Having .txt selected means non-spectra are highlighted (if you're in a folder with random text files).
    * It looks like these are maybe pluggable file openers? I can see why it is the way it is, but it would be a way better user experience for the program to figure out what files it can open, and open them correctly (JWST FITS vs. Keck FITS) without manual intervention.
  * The first thing you'll want to do is plot a newly opened data set, maybe not in every case but DEFINITELY in the case where there are no spectra currently plotted. A user might be surprised that their opened data set is not 'opened' (visible as a plot) until they click the unlabeled button below the data list control.
  * Less important, but after plotting the first spectrum, it would be nice to maximize that subwindow within the inner window area. (Also makes the lack of proper window shadowing on Mac OS X less obvious...)
  * The plot layout bugs me, as plot layouts determined programmatically often do. The 'Flux' label runs into the left edge of the subwindow. There is an axis/label saying '0 ... 1' that looks like it shouldn't be where it is in the top left. There should be a way to reset the plot bounds. (I see "View all" in the right click menu -- that should be a button with a label, somewhere obvious.)

## After plotting the data set

  * The menu bar on the plot subwindow seems somewhat mysterious. Not as mysterious as the overall top menu bar, but still pretty mysterious. What is the difference between the single gear dropdown and the two gears dropdown? Two gear dropdown seems to activate but no menu appears. I think some labels would go a long way. If there are no available items, the dropdown should be disabled and the button changed to indicate that.
  * Woah, what's all this in the right click menu on the plot control? I was trying to figure out how to export a figure (this would be a good menubar button!) and found a bunch of visualization controls! These should be more obvious. A lot of people will never go poking through right click menus. This is more what I expected clicking the single gear icon, actually.

## Model fitting

  * I can select some models for a model layer, and must "Create the layer" to make the fitting routine controls appear. This is kind of unintuitive, but I'm not sure what the solution should be. I'm having trouble articulating what exactly is surprising about it: I think it's that the Model Fitting pane is the "choose initial values and create a 'model layer' pane" and the "perform fitting" pane.
  * Tried fitting a Gaussian to one of the peaks in the spectrum, but no dice. I get a line through the peak. Oh, wait, the initial mean value isn't set by my measurement mode box. I guess I shouldn't have thought it could read my mind...
  * I can't change the color of my model overplot layer! I found the color control (death to right-click menus) and selected orange (it would be great to use some http://colorbrewer2.org qualitative maps to pick the first few layer colors). But the plot didn't update :(
  * The arithmetic box should include some indication of what the default behavior is. Is it to sum the models? Only fit the first one in the list? It's a cop out usability wise, but an example formula below the box would help to clarify how to use it.
    * Relatedly, I'm not sure how to use the "Layer arithmetic" box. Layer names don't seem to be required to be unique, and they have spaces in them which makes me feel weird about using them in arithmetic expressions... I subtracted `generic_spectra Layer` from `generic_spectra Layer` and didn't get zero, so I'm sure I'm misunderstanding.

**Comment by nmearl** [comment]
Closing this in favor of the forum topic [here](https://groups.google.com/forum/#!topic/specviz/B3MTJg4o_kM). It's a better venue for discussion, and individual improvements/enhancements can be opened as their own ticket.
