### ISSUE TITLE
Extend statistics module

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#20]
Include functions for

Stats that don't require a model
- [x] Centroid (API implemented in #39 but algorithm ~~needs correcting~~ corrected)
- [ ] ~~Center~~
- [x] FWZI (#39)

Stats that require a model
- [ ] FWHM
- [ ] Gaussian sigma (from moments or fitting)

See the [statistics module](https://github.com/nmearl/pyfocal/blob/3f67cc10d4de74c4d4a972fcc2ce209489046dd9/pyfocal/analysis/statistics.py) (currently being re purposed from previous sprint).

**Comment by pllim** [comment]
Centroid and FWHM can be derived, say, from a fitted Gaussian model. In that case, we can just use the built-in modeling functionality, no?

Not sure what FWZI is.

**Comment by nmearl** [comment]
Well, the centroid calculation doesn't require a Gaussian, but FWHM does. FWZI is the full width at zero intensity, or base width at the continuum of a broad line.

There are two scenarios I see for this. The current statistics that are shown on the GUI as on-the-fly calculations, that require no input from the user other than a defined region of the plot. The other scenario is when a user already has a fitted model, and wishes to extract more information from the model. I've updated the issue text to reflect this.

**Comment by pllim** [comment]
What are the assumptions when you compute stats directly from data? That it is noise-free? If not, do you mitigate the noise first?

**Comment by pllim** [comment]
Despite #24, I think I can probably take a stab at this. Since stats don't need the GUI component for testing.

**Comment by nmearl** [comment]
> What are the assumptions when you compute stats directly from data?

This is a good question. The statistics module is a product of Jonathan's, but I assume he went with the most simplistic implementation. That is, it makes no assumptions on the nature of the data and simply deals with it as if they were simple arrays of numeric values.

**Comment by hcferguson** [comment]
FWHM may or may not require a Gaussian. One standard option is to compute sigma from the first-moment of the relevant pixels and use 2.355*sigma as the estimate of FWHM.

**Comment by pllim** [comment]
What is the difference between "center" and "centroid"?

**Comment by pllim** [comment]
By the way, from the IRAF documentation of `splot`, I did not see any mention of FWZI nor calculating a centroid without a model, so I have no baseline to compare #39 results to. Please let me know if I missed something.

**Comment by pllim** [comment]
The stats that comes with modeling are naturally generated by fitted model.

**Comment by hcferguson** [comment]
Closing: Basic stats are now in SpecUtils and exposed in SpecViz. I don't think FWZI isn't there yet, though.
