### ISSUE TITLE
PyQt5 installation instructions need update?

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/specviz#202]
I found that this command from the documentation no longer works. 

camino:/Users/busko/Projects > conda install --channel https://anaconda.org/m-labs/pyqt5 pyqt5
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: .....Error: Could not find URL: https://anaconda.org/m-labs/pyqt5/osx-64/
camino:/Users/busko/Projects > 

I tried it first from my standard but possibly broken python environment. Then I tried it from a pristine environment that I had just created with conda. Still the same error.

Has anyone seen this before?

As a last resort, I also tried the instructions at https://anaconda.org/m-labs/pyqt5

but got this:

camino:/Users/busko/Projects > conda install -c m-labs pyqt5=5.5.1
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .
Error:  Package missing in current osx-64 channels: 
  - pyqt5 5.5.1*

You can search for this package on anaconda.org with

    anaconda search -t conda pyqt5 5.5.1*
camino:/Users/busko/Projects >

**Comment by nmearl** [comment]
Sorry, visit the site again -- was pointing to a slightly out of date version.

**Comment by nmearl** [comment]
I should explain that `m-labs` version is inter-operable between pyqt and pyqt5 (that is, it doesn't interfere with the installations), but it's windows only. 😞

**Comment by ibusko** [comment]
So, what is the link for the OS X version? I still get that same error.

**Comment by nmearl** [comment]
Try now, you should see:

```bash
$ conda install --channel https://conda.anaconda.org/spyder-ide pyqt5
$ conda install --channel https://conda.anaconda.org/nmearl specviz
```

**Comment by ibusko** [comment]
Thanks, that works!

Although I don't see it in http://specviz.readthedocs.io/en/latest/installation.html. Maybe there is latency somewhere in github?

**Comment by pllim** [comment]
According to https://readthedocs.org/projects/specviz/builds/ , the last doc build was 12 minutes ago. Try hitting refresh.

**Comment by ibusko** [comment]
Indeed. Latency in doc building.
