### ISSUE TITLE
Proper way to remove all data from data collection?

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/specviz#204]
I'd like to remove all loaded data objects. I tried doing `data_manager._members.clear()` but that didn't seem to work - is there a proper way to do this, and if not, what would be the best way to implement it?

**Comment by nmearl** [comment]
@astrofrog There isn't currently a built in function for that, but an easy way to propagation that data has been deleted would be to do something like [data_manager.remove(data) for data in data_manager._members].

**Comment by nmearl** [comment]
I should note (not necessarily relevant to you in this instance), but the manager abstraction will be removed in the next point release of SpecViz.

**Comment by astrofrog** [comment]
@nmearl - ok, sounds good. So at that point, could we make sure there is another way to clear the data collection? (should it be via the controller?)

**Comment by nmearl** [comment]
It will most likely be via the messaging system (`Dispatch.on_remove_all_data.emit()`), with a registered listener in the `data_list_plugin` that is responsible for storing/maintaining data sets.
