### ISSUE TITLE
Explore plot annotating in pyqtgraph

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#21]
This deals with incorporating over-plot templates; i.e. putting text annotation at certain points on the spectra.

Perhaps look into the [`TextItem`](http://www.pyqtgraph.org/documentation/graphicsItems/textitem.html).

**Comment by ibusko** [comment]
We will also need [`LabelItem`](http://www.pyqtgraph.org/documentation/graphicsItems/labelitem.html) so we can draw spectral line identifications such as these:

![example13](https://cloud.githubusercontent.com/assets/3577145/14431784/424082a2-ffd5-11e5-88f1-2188518d582a.jpeg)

**Comment by nmearl** [comment]
It can be done!
