### ISSUE TITLE
Line weights

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#220]
We'll need a way to adjust line weight in spite of performance penalties. The default line-weight on a Mac retina display makes the fitted model almost invisible if it isn't the foreground layer.
<img width="1356" alt="screen shot 2016-10-28 at 10 07 06 am" src="https://cloud.githubusercontent.com/assets/2261329/19809229/60eed5fa-9cf6-11e6-93fc-9c526df20409.png">

**Comment by nmearl** [comment]
The being "invisible" is actually a different effect. Basically, the alpha of the line color is reduced if it's not the foreground layer. Perhaps we should remove that behavior?

**Comment by hcferguson** [comment]
Ah. Yes, that sounds like a good quick fix.

**Comment by nmearl** [comment]
Added in afc971db04da24a94500a8e5100cb38e01d874e2.
