### ISSUE TITLE
Redshift as a model

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#231]
It's not obvious what "redshift" means as a model. Is it multiplying the wavelengths by 1+z before fitting? This needs some documentation.

When I selected it as a model, having already selected a constant and a Gaussian, it put it in as a separate component to add to the other two. That's not a sensible behavior. We'll need a way to represent changing the independent variable to be a function of some other model.

**Comment by pllim** [comment]
As far as model representation is concerned, it is valid to see redshift as a separate model. No matter how you package it, that is how modeling works.

**Comment by ibusko** [comment]
The Redshift model in astropy was deprecated and replaced by RedshiftScaleFactor, which is defined as 

f(x) = x (1 + z)

Thus, in the context of a compound model, it is just a linear ramp that increases with wavelength by a factor 1+z. I think that in order to apply a redshift operation in specviz it should be handled separately from the model fitting machinery. That is, it won't be possible to "fit for the best redshift", whatever that means.

I tried composing gaussians and redshifts in a notebook to confirm the behavior.

I sugest we remove for now the Redshift entry in specviz's model list

**Comment by ibusko** [comment]
In the context of model fitting, redshift could be handled in two different ways:

1.  Redshift/blueshift the data to the co-moving frame (or any desired *z*), and fit model in this frame.

2. Leave data intact and build model components that include a redshift parameter that is used to correct
the other component parameters at the time the component is rendered on the wavelength array, as part of a compound model.

Each one has its pros and cons, but from the outset I can see that (1) is way easier to implement than (2) (it's the solution we adopted in the old Java specview app). Which one makes more sense from both the science requirements viewpoint, and from the operational/GUI viewpoint, I think deserves an in-depth discussion.

Here are some thoughts, a few of them backed by experiments (recorded in a notebook):

Solution 1:
  - pros:
    - straightforward to implement. 
    - redshift transformation exists outside of the context of modeling, that is, can be applied to any spectrum that lives inside the app.
    - model won't be specific to any particular value of *z*.
  - cons:
    - *z* won't be a fitable parameter.
    - *z* won't be recorded as part of the model, when the model is written out to file.
    - won't support multiple values of *z* for a single model fit. Is there a science case for this? I though of something like a Lyalpha forest. 

Solution 2:
  - pros:
    - *z* is a fitable parameter.
    - intrinsically support independent values of *z* for each component in a compound model.
  - cons:
    - *z* (or its multiple values) is tied to any given model.
    - cannot redshift/blueshift the data themselves. Unless we put in that functionality explicitly. That can make the whole redshift business a bit confusing, because users will be able to apply model components with a redshift transformation, on data that is already transformed by redshift. 
    - can't use astropy.modeling functions directly to build a compound model. All astropy models must be overridden so as to accommodate an additional parameter (*z*). Internal calculations get more complex because, for getting first guesses for the parameters, the units-related corrections associated to a redshift transformation (photon time of arrival, and bin size stretch) must be applied to the flux and width-related parameters in each component in a component-dependent way. Maybe by enforcing flux conservation for some component types, or directly applying units-related corrections  for other types. Doesn't really matter as long as we have the guesses reasonably close to the "truth".
    - implementing simultaneous/tied fit of all (or many) redshift parameters in all components of a compound model will make the UI (and likely the internal implementation) more complicated. This particular mode of operation must be addressed from the outset since it is likely to be the most common use of the redshift fit ability.

**Comment by hcferguson** [comment]
Thanks for writing out the pros and cons. 

It's worth thinking more about (2), because having z be fittable is an attractive feature.  The third bullet in this list isn't strictly true -- in the sense that Astropy compound models already allow one to build a model where redshift is a parameter (fixed or fittable). There is an example of this in the documentation http://docs.astropy.org/en/stable/modeling/compound-models.html. I have tried an experiment of having redshift be fittable but the mean of the gaussian be fix and that works if I give reasonable guesses. Obviously freeing both won't work because they are degenerate. 

I agree that there is confusion if someone redshifts the spectrum. However, we don't adjust the data when we apply the redshift...just adjust the axis labels, I think. Right @nmearl?

Anyway...I want to keep (2) open at least to flesh it out a bit more in concept.

**Comment by ibusko** [comment]
Ah, OK, there is composition. I completely overlooked that. That means the second bullet isn't indeed true. In that case, specviz could do it almost as is, isn't? As long as the user modifies the expression by replacing the '+' by the composition symbol whenever appropriate.

As for not adjusting the data when applying redshift, shouldn't it be adjusting the fluxes? Redshifting will change the fluxes (and any spectral slope if the wavelength range is wide enough) unless the spectrum is expressed in photon-nu units.

**Comment by hcferguson** [comment]
I agree we need to think about treatment of fluxes when redshifting. True even if not redshifted. A Gaussian in set of flux units is not going to be a Gaussian in a different set. So are we always specifying the models in the units shown *on the plot* or are we specifying them in the units that are native to the WCS or some other units?  

Probably should open a new issue for this.

**Comment by ibusko** [comment]
Here I put some thoughts on redshift conversions. Just for observed spectra, didn't work with astropy models yet:  https://github.com/ibusko/experiments_specviz/blob/master/experiment_redshift.ipynb

**Comment by kassin** [comment]
Discussion: Probably too generalized a way of getting z's.  Let's look into different z finders.
