### ISSUE TITLE
doc strings for ALL

### ISSUE THREAD

**Issue by justincely** [spacetelescope/specviz#237]
Attempt to put docstrings on everything in order to learn the code and help contributions.

**Comment by stscieisenhamer** [comment]
# Implementation
File list:
- [ ] analysis
    - [ ] models
        - [ ] blackbody.py
        - [ ] spline.py
    - [ ] statistics.py
    - [ ] utils.py
- [ ] core
- [ ] data
- [ ] external
- [ ] interfaces
- [ ] io
- [ ] plugins
- [ ] tests
- [ ] third_party
- [ ] ui

**Comment by pllim** [comment]
Is it really necessary to document "external", "tests", and "third_party"?

**Comment by justincely** [comment]
I've opened PR #238 for some work towards this.  So far, i only enabled the following in the import process, so these should focus on API-level documentation

- analysis
- core
- data
- interfaces
- io
- ui

External and third_party should at least get a module docstring at the top describing any amount of information that may be necessary on how/when to add packages into the modules, how they're used, etc.  But these won't need to be exposed in the import or API (in-fact, some couldn't be with the current import scheme - they'd start creating Qt windows and cause errors)

**Comment by justincely** [comment]
Done

**Comment by nmearl** [comment]
Thanks for your hard work, @stscieisenhamer!
