### ISSUE TITLE
Duplication of code between interfaces/model_io and io/model_io

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/specviz#240]

**Comment by nmearl** [comment]
Are both used?

**Comment by stscieisenhamer** [comment]
@ibusko Would you know about this?

**Comment by ibusko** [comment]
From the history records, I can see that the interfaces/model_io was created first (Feb 2016) and the io/model_io came later (June 2016). Their contents look identical though.

**Comment by nmearl** [comment]
Nothing in `io/model_io` is used; it can safely be removed.
