### ISSUE TITLE
Display select row/line of a table, image, cube

### ISSUE THREAD

**Issue by justincely** [spacetelescope/specviz#242]
SPLOT had the ability to select and plot select 1D data from higher-dimensional datasets.  This could be:

- a specific Column from a table
- a specific row or column from an image
- a 1D array along any axis of a 3D cube.
- a specific aperture in a multi-aperture spectra file

Specviz should be able to do this and select the parameters from the command-line.

**Comment by hcferguson** [comment]
Cubeviz should handle the cube case.
The simplest 2-D use case is an image where each row is a separate 1-D spectrum. 

A much more complicated case would be selecting spectra from HST grism data to plot in Specviz. This might involve communicating between a 2D display (Glue or Ginga) and Specviz.

**Comment by ibusko** [comment]
The 2-D (image) to 1-D operation is complex enough that it should be done somewhere else. Think optimal extraction, or scattered light correction for echelles. Isn't specviz supposed to be a 1-D tool? It's fine to be able to recognize formats that store multiple 1-D spectra in a single file, but I think it should stop at that.

**Comment by hcferguson** [comment]
Closing this. The wizard will handle the first case. Cubeviz will handle the cube. Issue #515  discusses the case of collections of spectra. 

The missing case is when the spectra are packaged in a 2D image with one spectrum per row (wavelength is one axis; spectrum ID is the other). Usually such images are constructed from extracted spectra for visualization purposes, so the user probably has the spectra in a different sort of collection already that might be more amenable to the wizard.
