### ISSUE TITLE
arithmetic function mode

### ISSUE THREAD

**Issue by justincely** [spacetelescope/specviz#245]
SPLOT contains the ability to perform arithmetic to the spectra, such as:

- Absolute value
- Power of base 10 (inverse log base 10)
- Power of base e (inverse log base e)
- Inverse/reciprocal (values equal to zero are set to 0.0 in the inverse)
- Log base 10 (values less than or equal to 0.0 are set to -0.5)
- Multiply by a constant (constant is queried)
- Log base e (values less than or equal to 0.0 are set to -0.5)
- Add by a constant (constant is queried)
- Square root (values less than 0.0 are set to 0.0)
- Add another spectrum
- Subtract another spectrum
- Multiply by another spectrum
- Divide by another spectrum

SpecViz should also contain much of this capability.  

When the second operand of an arithmetic operation is a spectrum, operations should be done in wavelength space and interpolated as necessary

**Comment by pllim** [comment]
This is more an issue for specutils or pysynphot, whichever one you plan to use with specviz. IMHO the codes here should just focus on the visualization part. Calculation and spectra manipulation belong somewhere else.

**Comment by justincely** [comment]
I agree @pllim, we'll just need some surface interface to perform the various arith.

**Comment by nmearl** [comment]
All non-function-based operations are already supported via the button under the layer list that looks like arithmetic operators.

- [ ] Absolute value
- [ ] Power of base 10 (inverse log base 10)
- [ ] Power of base e (inverse log base e)
- [ ] Inverse/reciprocal (values equal to zero are set to 0.0 in the inverse)
- [ ] Log base 10 (values less than or equal to 0.0 are set to -0.5)
- [x] Multiply by a constant (constant is queried)
- [ ] Log base e (values less than or equal to 0.0 are set to -0.5)
- [x] Add by a constant (constant is queried)
- [ ] Square root (values less than 0.0 are set to 0.0)
- [x] Add another spectrum
- [x] Subtract another spectrum
- [x] Multiply by another spectrum
- [x] Divide by another spectrum
