### ISSUE TITLE
Easier way to view the residuals

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#253]
The workflow for viewing the residuals (and accompanying statistics -- goodness of fit) should be very simple. Needs discussion.

**Comment by ibusko** [comment]
Based on what I saw in the development of Java specview and Iris, I think the residuals and associated statistics should be an integral part of a model-data association. In these two older softwares, a model can't exist by itself unless when it is dumped to an external medium. Inside the application, a model only exists associated to one or more pieces of data. Each one of these associations has a 'residuals' property that does not depend on the fact the model was actually fitted to the data or not. 

From the operational point of view, in those older apps as soon as the user associates a model with data, residuals will automatically be plotted in the same window as the data, and statistics such as chi-sq will be displayed by the GUI regardless if a fit has been performed or not. Of course, in specviz we could refrain from the automatic actual display/plot part and leave that to be initiated by the user. But having the residuals as an integral part of the model-data association makes sense from the architectural viewpoint anyway.
