### ISSUE TITLE
Example spectra in specviz/specviz/data are broken

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/specviz#254]
Two spectra in the specviz/specviz/data directory have the wavelength units defined as None. This causes a crash-and-burn inside astropy/units/core.py when one tries to enter a units value using the Units menu button and dialog.

The spectra are spec1d.1245.066.12004136.fits and spec1d.gds1312_H0.003.emp26177.fits

**Comment by kassin** [comment]
see data loaders issue

**Comment by kassin** [comment]
Tom is addressing this with the data loader wizard in #292  

Most users will have non-standard files like these.  I sent a bunch of non-standard spectra to Tom to help build the wizard.
