### ISSUE TITLE
Blackbody model is broken.

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/specviz#272]
The Blackbody model requires that both the flux and wave arrays be Quantity arrays, that is, they must have units attached to them so a Planck function can be computed.

This used to work before, but now the caller (in model_fitting_plugin.py) passes bare numpy arrays to both the initializer instance and the 'evaluate' method. The doc strings in blackbody.py are outdated and maybe this led to confusion. 

We must either temporarily remove Blackbody from the list of model options, or must provide default units for spectra that don't have units defined in their metadata.

**Comment by mattjhill** [comment]
Whoops, I made that changed to deal with LogQuantities and didn't realize the Blackbody initializer needs units.

**Comment by nmearl** [comment]
As of #273, this has been removed from the models.
