### ISSUE TITLE
BUG: specviz tries to run all python scripts in current working directory

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/specviz#274]
If I install the latest version of specviz and try and run ``specviz``, it will try and run every single Python script in the current working directory. For example if I put a print statement at the top of scripts called 'test.py' and 'script.py' in the current working directory and start specviz, I get:

```
$ specviz
INFO:root:Added Simple Fits to loader registry.
INFO:root:Added HST/COS to loader registry.
INFO:root:Added HST/STIS to loader registry.
INFO:root:Dispatch is now watching: <specviz.ui.widgets.windows.MainWindow object at 0x1209eb048>
RUNNING SCRIPT
INFO:root:Dispatch is now watching: <specviz.ui.widgets.windows.MainWindow object at 0x12c944828>
WARNING:root:Unable to import race_condition in /Users/tom/Data/Spectra.
running script.py
INFO:root:Dispatch is now watching: <specviz.ui.widgets.windows.MainWindow object at 0x12c944ee8>
WARNING:root:Unable to import script in /Users/tom/Data/Spectra.
running test.py
```

Note the 'running' messages. I don't think this would be expected behavior by users and should IMHO be fixed for the release. If you want specviz to automatically load certain kinds of models, I would recommend an approach like in glue where we whitelist specifically a certain filename (``config.py``). Maybe here you could whitelist ``specviz_models.py`` or similar?

**Comment by nmearl** [comment]
This is somewhat intentional, see #185. I'm not sure whitelisting is practical since there is no imposed naming convention for python custom loader files.

The middle ground could be to load *only* yaml files from the current directory.

Personally, I think the user should be responsible for moving specviz-specific loader files to their `~/.specviz` directories.

@hcferguson @pllim Thoughts?

**Comment by astrofrog** [comment]
I think loading all Python scripts is definitely going to cause a lot of confusion, and I would support only loading Python files from a ``.specviz`` directory. Note that for custom loader files, you could certainly choose to impose a convention, for example that the name has to start with specviz?

**Comment by mattjhill** [comment]
I would also vote for only loading files from the `.specviz` directory

**Comment by hcferguson** [comment]
I think loading all python scripts creates a gaping security hole. 
Are the YAML loader files executable? I thought they were just being read in and we had disabled the ability to include executable code in them.

**Comment by hcferguson** [comment]
That said...I think there is a lot of value in being able to have the custom loaders in the same directory as the data. So what is the downside of making the YAML files not executable?

**Comment by nmearl** [comment]
I'm not sure what you mean by the yaml files being executable? They're just a data serialization format. They get loaded in and parsed by specviz.

**Comment by hcferguson** [comment]
One wants to make sure to use yaml.safe_load...
https://security.openstack.org/guidelines/dg_avoid-dangerous-input-parsing-libraries.html

**Comment by nmearl** [comment]
Ah, I see what you mean. Unfortunately, we need `yaml.load`, because it parses the yaml file directly into a registry object. `safe_load`, if I recall, requires that the yaml file be parsed to only simple python objects.

We may need to reconsider how we parse the yaml files, then.

**Comment by hcferguson** [comment]
Is the issue with wanting to execute python scripts related to custom models, rather than custom loaders? I think it's perfectly fine to require custom models to be put in ~/.specviz.

**Comment by pllim** [comment]
Definitely should not run all the scripts. Just `*.yml` should be sufficient, no? I have not been in the loop of this sprint for a while but I vaguely remember users wanted to be able to load YAML from working directory.

**Comment by nmearl** [comment]
Just yaml isn't sufficient because users can create custom loader python functions.

**Comment by astrofrog** [comment]
One idea would be to read everything from ``~/.specviz`` but also allow users to pass arguments to specviz, e.g.:

```
specviz --config myconfig.yml
```

**Comment by nmearl** [comment]
I'm not sure that I follow. My understanding is that the issue isn't really about loading configuration settings (there technically is no specivz configuration file at the moment). Instead, whether or not the user is allowed to launch specviz from a specific directory that contains custom loader or custom model python files that *could* be loaded into specviz.

**Comment by astrofrog** [comment]
@nmearl - sorry, I was unclear: what I mean is that if the custom loader files are not in ~/.specviz, we could require users to specify them explicitly on the command line when launching specviz. So maybe something like:

```
specviz --custom-loader=myloaders.py
```
