### ISSUE TITLE
BUG: reading multiple files by emitting 'on_file_read'

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/specviz#275]
I think there is an issue when multiple ``on_file_read`` events are fired in quick successions. The following example illustrates the problem:

```python
import glob

from qtpy.QtWidgets import QApplication

from specviz.core import dispatch
from specviz.ui.viewer import Viewer

app = QApplication([''])

viewer = Viewer()

for filename in glob.glob('*spec*.fits'):

    print('Loading spectrum from ', filename)

    dispatch.on_file_read.emit(file_name=filename,
                               file_filter='MOS')

viewer.main_window.show()
app.exec_()
```

Note that because of #274 I had to make a directory with just the spectra and run the script located elsewhere, by doing e.g. ``python ../script.py`` (otherwise there was some kind of recursion). When running this, only one (the last) spectrum is read into specviz. If I add a ``time.sleep(1)`` inside the loop, then multiple datasets show up.

This causes the glue plugin to not work correctly and only show one of the spectra from the selected subsets.

**Comment by nmearl** [comment]
This was expected (but not ideal). It's a consequence of keeping access to a single thread. If the thread doesn't return before it's called again, it will ignore the initial inputs.

There is a quick fix for this.

**Comment by nmearl** [comment]
@astrofrog Try your script with the latest merge.

**Comment by astrofrog** [comment]
It works! I have a new related issue though, but I think it's a separate bug - will open a new ticket.
