### ISSUE TITLE
Independently scale flux & wavelength axes

### ISSUE THREAD

**Issue by weaverba137** [spacetelescope/specviz#287]
Is it possible to independently scale the x and y (wavelength & flux) axes? Some spectra I have loaded recently have very large uncertainties, especially on known sky lines, & the scale of the errors appears to set the scale of the y axis. In other words, I'd like to zoom the flux axis while not zooming the wavelength axis.

**Comment by hcferguson** [comment]
If you move your cursor down below the x-axis, you can scale just x. If you move to the left of the y-axis you can scale just y.

**Comment by weaverba137** [comment]
Ah, got it, thanx!
