### ISSUE TITLE
Use of 'import *' in code

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/specviz#290]
The use of e.g.

```
from qtpy.QtWidgets import *
```

in the code makes it impossible to use static code checkers, and pollutes the namespace with many classes/functions. It would be better to do:

```
from qtpy import QtWidgets
```

then refer to widgets with e.g. ``QtWidget.QWidget``. If others agree I could go through and try and fix this.

**Comment by nmearl** [comment]
When it comes to `Qt`, my main preference is to import only what needs to be used. With the `Q` prefix on all the classes, it serves the purpose of being pretty explicitly from the `Qt` library. 

```
from qtpy.QtWidgets import QWidget
```

But, second best, I think, is importing the module and calling classes from that namespace. Either way, you have my support over the blanket import.

**Comment by astrofrog** [comment]
@nmearl - I agree with using ``from qtpy.QtWidgets import QWidget`` - anything other than ``*`` ;) I can work on that.

**Comment by SaOgaz** [comment]
A repo search seems to indicate that this is resolved, can we close this @astrofrog?
