### ISSUE TITLE
data loader wizard

### ISSUE THREAD

**Issue by kassin** [spacetelescope/specviz#292]

**Comment by nmearl** [comment]
@astrofrog It seems I'm running into some edge cases with the wizard. For starter, the general `general_spectra.fits` file doesn't seem to be recognized at all by the wizard. Same with much of the nominal SpecViz data.

Second, I'm wondering... it's quite common for a data set to not have an explicit dispersion array (instead, expecting it to be composed from the WCS). Technically, this is supported by the `Spectrum1DRef` object, but maybe we ought to have a checkbox that says something like "compose dispersion from WCS" when it detects that there is actually a WCS object available.

**Comment by astrofrog** [comment]
@nmearl - in principle I think the wizard should already deal with the second case. If a spectral WCS is present, it will show up as a component. I'll investigate why ``general_spectra.fits`` isn't working though.
