### ISSUE TITLE
BUG: too many models getting added

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/specviz#293]
Easier to explain in a video than in words:

![output](https://cloud.githubusercontent.com/assets/314716/26797280/43695f42-4a24-11e7-9291-4422a180ad83.gif)

When I add a gaussian then add a linear model, a second gaussian gets added.

**Comment by nmearl** [comment]
I'm not seeing this. Is this from a clean specviz install?

**Comment by ibusko** [comment]
I don't see this either.

**Comment by kassin** [comment]
Me neither.

**Comment by nmearl** [comment]
@astrofrog Are you still seeing this issue?

**Comment by nmearl** [comment]
Currently, I can't find any instance of this happening. I'm going to close this until the problem returns.
