### ISSUE TITLE
Allow resampling of data sets

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#297]
Make it so data sets can be plotted on the same wavelength grid. This requires prompting the user when the grids are different and offer varying interpolation techniques. Perhaps have some indication that a particular layer on a plot *has* been interpolated.

**Comment by nmearl** [comment]
Related to #245.

**Comment by nmearl** [comment]
@hcferguson @kassin I'm concerned that simple interpolation is insufficient because it does not conserve flux. Is this something we should consider?

**Comment by hcferguson** [comment]
Yes, definitely something to consider.

**Comment by kassin** [comment]
It should conserve flux.  Unless you are also redshifting the spectra or the spectra are of very high S/N.
