### ISSUE TITLE
Bug in 1-button mode mouse

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/specviz#298]
When zooming with the rubber-band yellow box, the box is incorrectly drawn when the departing point is the top left corner of the box. In the other three possible cases, the box displays fine. Note that the zoom operation that results is always correct, it's just the yellow box that is incorrect.

**Comment by ibusko** [comment]
I detected this under Mac OS X 10.10.5, on two different machines. Following the suggestion that it could be a version issue, I re-installed specviz from scratch on a brand new conda environment. The problem still persists. I am assuming now that it is OS-related.

**Comment by hcferguson** [comment]
@ibusko is this still a problem in the current version?
