### ISSUE TITLE
feature detection plugin

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#304]
A common workflow might be to run a feature-detection filter (e.g. to search for emission lines or absorption lines) and then inspect the results. These can get pretty fancy, so it probably makes sense to code up a basic one as an example and then let people use that as a template for building fancier plugins. The simplest useful detection algorithm is the following:

- Convolve the spectrum with a fixed kernel (usually a Gaussian with FWHM corresponding to the spectral resolution).
- Divide by the RMS noise and search for pixels above or below a fixed S/N threshold. These are the emission or absorption line centers. 
 
Features of the basic one might include

- Gaussian smoothing kernel with user-specifiable width.
- Noise RMS taken from the error array or computed from a single ROI
- Detected features marked somehow on the plot (e.g. overlaid gaussians? ticks? ROIs?)
- Generate a table of wavelength, S/N, flux, FWHM and EW for each feature. 
- Varying the "number of connected pixels" required for a detection.

Items probably out of scope for a basic feature detector:

- Different functional forms for kernels
- Smoothly varying S/N estimated from multiple ROIs
- Feature de-blending
- Fancy local-continuum estimation when generating the table of values
- Constrained detection of common transitions (e.g. doublets)
- Identifying the features (e.g. [OIII] 5007)

**Comment by ibusko** [comment]
I put together a few simple experiments in here:  https://github.com/ibusko/experiments_specviz/blob/master/experiment_feature_detection.ipynb

**Comment by hcferguson** [comment]
This is being worked on in SpecUtils and will be exposed in SpecViz after that's ready. [SpecUtils PR362](https://github.com/astropy/specutils/pull/362)
