### ISSUE TITLE
New user experience: zooming (flux-axis) is not intuitive

### ISSUE THREAD

**Issue by eteq** [spacetelescope/specviz#321]
I recently tried loading in a DEIMOS file with some bad pixels (which are orders-of-magnitude bigger than the spectrum itself).  When it pops up, it's not at all clear how to zoom in so that the *real* pixels are at a reasonable scale.  This should be much more prominent, possibly including a way to click on a *button* somewhere to get the right-click menu?

**Comment by eteq** [comment]
Just to clarify, I know the solution is to right-click and go to the manual setting.  But it's really not obvious to a new user that you have to right-click.  So it might be that there needs to be another way to do the zooming *or* the "right-click to get these settings" part has to be more prominent.

**Comment by SaOgaz** [comment]
In a test session with @bethanjames, she requested a box style zoom.  As in, you left click on the mouse to draw a box on the plot, and that's your zoom window.

**Comment by nmearl** [comment]
@eteq Right clicking is disabled in the plot -- what version of the application are you using that you're able to right click?
