### ISSUE TITLE
Wizard incorrectly names HDU's

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#323]
The wizard seems to like to name HDU's as "HDU \<index\>" for display purposes, but that name doesn't actually exist in the fits file. This causes an issue when trying to open the file

```
INFO:root:Attempting to open '/Users/nearl/Downloads/UDF_00126.1D.fits' using YAML loader 'e6037cf8-46ac-41fd-ae1d-5245ef3bfcb7'
ERROR:root:Incompatible loader for selected data: e6037cf8-46ac-41fd-ae1d-5245ef3bfcb7 (*.fits *fits.gz) because "Extension 'HDU 1' not found."
ERROR:root:Could not open file.
```

It is unable to find the extension, since none are actually *named* "HDU \<index\>". This is also the case when you save out the loader configuration; you can see that the `hdu` is being tagged to the constructed name instead of the actual integer index (for the case where the extension is not actually named anything, I would expect that if the extension was named something that would be preserved).

**Comment by astrofrog** [comment]
Oops you are right, I'll take a look
