### ISSUE TITLE
Write tests for non-GUI functionalities

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#33]
For example, we need tests to ensure that the analysis functions give the correct answers. This will also require some basic test data to go with the repo.

**Comment by justincely** [comment]
Lets add a list of tests that should be done at some point, and @mattjhill can work on implementing them

**Comment by hcferguson** [comment]
Since all the analysis is now in Specutils, tests on "correct answers" are going there. Closing this, even though we will still want to have UI tests to make sure that the correct answers are what is appearing in the UI output boxes.
