### ISSUE TITLE
Wizard for tabular 1D spectra

### ISSUE THREAD

**Issue by kassin** [spacetelescope/specviz#331]
It would be great to have a wizard that helps readers read in spectra in ascii format
like those in:

/astro/3/jwst_da_sprint_testdata/SpecViz/PN_Muzerolle

**Comment by astrofrog** [comment]
I agree - I wrote the wizard in a way that in principle it could be extended for non-FITS files too, so hopefully it shouldn't be too much work

**Comment by ibusko** [comment]
I bet this could be done easily with the ECSV format.

**Comment by ibusko** [comment]
This could be alternatively done using the ECSV format.

**Comment by ibusko** [comment]
I updated the wizard to read ECSV text files.

**Comment by ibusko** [comment]
Wizard updated to accept ASCII tables.
