### ISSUE TITLE
Warnings about unclosed files

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/specviz#332]
I see a lot of warnings like this:

```
/Users/tom/miniconda3/envs/dev/lib/python3.6/site-packages/specviz/interfaces/loaders.py:23: ResourceWarning: unclosed file <_io.TextIOWrapper name='/Users/tom/.specviz/myreader.yaml' mode='r' encoding='UTF-8'>
    custom_loader = yaml.load(open(f_path, 'r'))
```

when running the glue test suite, so it would be good to close the YAML file.

**Comment by drdavella** [comment]
Would it make sense to use [pytest-openfiles](https://github.com/astropy/pytest-openfiles) here?

**Comment by nmearl** [comment]
This is a pretty minor fix, but I think another issue should be opened to add a test for dangling file object pointers.

**Comment by astrofrog** [comment]
As @drdavella said, just using pytest-openfiles might be sufficient here with the existing tests

**Comment by javerbukh** [comment]
No longer using YAML files.
