### ISSUE TITLE
Installation using miniconda?

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#334]
Hi again, Harry et al.,

Just before I left work on Friday I succeeded in downloading specviz using miniconda2 (rather than astroconda) using the command as in the instructions, and it seemed to work in that I got the Gui view when I invoked specviz.  I did this because I already had miniconda2 on my desktop.

When I got home, I tried the same command (conda install specviz), and specviz was downloaded with miniconda3, since I apparently had miniconda on my laptop rather than miniconda2 or astroconda.  This time it didn’t work, unfortunately, since one module (pkg_resources) apparently did not download - my bad.  See the attached screenshot.  How would you recommend that I continue from here on my laptop, and perhaps on my desktop, because of using the minconda2 & 3 environments?

Thanks in advance,
Jackie

<img width="746" alt="downloadmessages" src="https://user-images.githubusercontent.com/2261329/32445430-a9288312-c2d3-11e7-9dde-0099bc549ff1.png">

**Comment by nmearl** [comment]
> Hey Jacqueline,
>  
> A `No module named pkg_resources` error can indicate that you don’t have the `setuptools` package installed (which is strange, because it should be automatically installed when you install anaconda or pip).
>  
> Try running
>  
> `$ conda install setuptools`
>  
> And then
>  
> `$ conda install specviz`
>  
> --
> Nicholas Earl
> Space Telescope Science Institute
