### ISSUE TITLE
default line weight should be heavier than option 3

### ISSUE THREAD

**Issue by kassin** [spacetelescope/specviz#347]
When spectra are displayed the default line width should be heavier than even option 3.

**Comment by ibusko** [comment]
Made the default 3, and added a '4' option to the menu. '3' looked to me too heavy already, but it could be dependent on the actual data I used for testing.

**Comment by ibusko** [comment]
Reverted for now:

The default line width should stay 1 for performance reasons. Perhaps in the future the default will be settable by the user, but I think we should err on the side of having fast, interactive plots initially.
