### ISSUE TITLE
Where is the inverse variance equivalent of astropy.nddata.StdDevUncertainty defined?

### ISSUE THREAD

**Issue by weaverba137** [spacetelescope/specviz#355]
I need to write a Python loader for a spectrum that uses inverse variance for uncertainty, but I can't find the equivalent of `astropy.nddata.StdDevUncertainty`.  I looked in astropy itself, in specutils and in the specviz package.

**Comment by stscicrawford** [comment]
@weaverba137 Please raise this in the main astropy repo -- it would be great to add a class to do this, and a pull request related to this would be very welcome for this.

**Comment by javerbukh** [comment]
Should this be handled by the loader? Or should it be handled in Specutils?
