### ISSUE TITLE
Allow for builds against development versions of specutils

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/specviz#358]
Right now the requirement is expressed as `specutils==0.2.2`. This means it is not possible to build against development versions of `specutils`. This causes problems particularly when trying to use `astroconda-dev` to test rolling development builds. Could this requirement be updated to `specutils>=0.2.2`?

**Comment by nmearl** [comment]
No, anything above `specutils==0.2.2` is not backwards compatible.
