### ISSUE TITLE
Scientific notation not updating on unit change

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/specviz#361]
When cubeviz sends a unit conversion change to specviz, the units change but the scientific notation does not appear to update until I move the specviz plot (which then appears to update the x-axis label):

Cubeviz sends unit conversion change from mm to nm:
![image](https://user-images.githubusercontent.com/18348847/36265522-5d1e42fe-123d-11e8-81ca-6e2a62b983da.png)

After a movement in the specviz graph:
![image](https://user-images.githubusercontent.com/18348847/36265529-645edc22-123d-11e8-90ae-c7e425997276.png)

Note the correct removal after the *1e-6 part.  It seems there is a re-draw that is not firing on unit conversion signal.

**Comment by kassin** [comment]
good catch

**Comment by nmearl** [comment]
Is this still an issue?

**Comment by brechmos-stsci** [comment]
Yes. To see, change the dispersion units in Cubeviz. The bottom axis of specviz will change units but the (x1e-06) will not go away until you actually click once on the specviz plot.

**Comment by javerbukh** [comment]
Solved with #480
