### ISSUE TITLE
specviz fitting from within cubeviz

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/specviz#366]
I am on master for specviz and cubeviz and I am loading up the file `manga-7495-12704-LOGCUBE.fits.gz` in cubeviz.

When cubeviz comes up, I clicked on "Show Viewer Options" and clicked on the specviz window in order to bring up the "Plot Options - Specviz Viewer" bar on the bottom left hand side. In the dropdown I selected "Gaussian" and then hit the "Select" button.  I see the Guassian0 in the "Current Models" but there is also an error that comes up in the terminal:
```
ERROR:root:Received unknown command line arguments.
/Users/crjones/Documents/DATB/cubeviz/spectral-cube/spectral_cube/utils.py:39: UserWarning:

This function (<function BaseSpectralCube.sum at 0x181dfda7b8>) requires loading the entire cube into memory and may therefore be slow.

ERROR:root:Failed to convert x-axis plot units from [m] to [].
ERROR:root:Failed to convert y-axis plot units from [] to [1E-17 erg/s/cm^2/A/spaxel].
WARNING:root:Units are not compatible.
ERROR:root:Failed to convert x-axis plot units from [m] to [].
ERROR:root:Failed to convert y-axis plot units from [] to [1E-17 erg/s/cm^2/A/spaxel].
WARNING:root:Units are not compatible.
ERROR:root:Unable to convert x axis units of 'manga: manga-7495-12704-LOGCUBE.fits Layer Model Layer' to current plot units.
ERROR:root:Exception in 'update_plot':
Traceback (most recent call last):
  File "/Users/crjones/Documents/DATB/cubeviz/specviz/specviz/core/dispatch.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "/Users/crjones/Documents/DATB/cubeviz/specviz/specviz/widgets/sub_windows.py", line 345, in update_plot
    plot.update()
AttributeError: 'NoneType' object has no attribute 'update'
```

I think it stops the flow. I tried hitting "Perform Fit" anyway and it gave me:
```
ERROR:root:Attempting to fit model on a non ModelLayer.
```
and I don't see an Gaussian (with the initial conditions nor fitted)

**Comment by brechmos-stsci** [comment]
An an aside, not sure if it is related. I tried creating two models... a Gaussian and a Const in the hopes it would fit a gaussian with a baseline. But when I press Select with Const selected it replaces the "Current Models" Gaussian with the Const (and only Const).  Maybe I am misunderstanding how the fitting works.

**Comment by kassin** [comment]
@nmearl

**Comment by nmearl** [comment]
Hmm, I cannot replicate this problem. Fitting works flawlessly for me. I don't think I've made any huge recent changes lately, but you might want to try again? Here's a video of the typical work flow (also, it seems like the Glue image viewers don't want to show up on linux @astrofrog. I wonder if @ddavella sees this too.)

https://stsci.app.box.com/file/281505881586

**Comment by drdavella** [comment]
@nmearl I have been doing most of my development on the mac lately, but I just tried this on a Linux VM and see the same issue. It looks like the problem is coming from `glue`, so maybe @astrofrog has an idea? I just tried to bisect in `glue` but either the problem has existed for quite a while now (doesn't seem likely) or this is maybe an issue with a newer version of `matplotlib`?

**Comment by drdavella** [comment]
I just downgraded `matplotlib` from `2.2.0` to `2.1.0` and the viewers seem to be working again. 

cc @astrofrog

**Comment by drdavella** [comment]
https://github.com/glue-viz/glue/issues/1565

**Comment by brechmos-stsci** [comment]
> https://stsci.app.box.com/file/281505881586

@nmearl I tried watching the video but it doesn't seem to exist at that location:
![image](https://user-images.githubusercontent.com/18348847/37093778-8e46b392-21de-11e8-8824-0d24de2aa23b.png)

**Comment by brechmos-stsci** [comment]
I did another git pull on specviz master and it looks like it might have been one of the two changes late last week as it now works. I'll close this...

**Comment by nmearl** [comment]
@brechmos-stsci [for posterity, give this link a go.](https://stsci.box.com/s/hxgu376ichct51i5uicbekenpw8l89f5)
