### ISSUE TITLE
Spectral smoothing Standard Deviation needs units

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/specviz#376]
The users are not finding it clear what the units are for the Standard Deviation (pixels vs actual astronomical units).

![image](https://user-images.githubusercontent.com/18348847/37596292-13ea4910-2b52-11e8-9edc-185009e0bf3f.png)

Related to cubeviz view.

**Comment by ibusko** [comment]
Fixed to look like this:

![untitled](https://user-images.githubusercontent.com/3577145/38507579-ed3f3290-3bea-11e8-8102-2904dcd91105.jpg)
