### ISSUE TITLE
Auto-crop the limits of the viewer to the data

### ISSUE THREAD

**Issue by Cadair** [spacetelescope/specviz#378]
I have a dataset that only has ~20 points close together in wavelength space, when I open a new specviz viewer, it takes me much zooming around to find the actual data. 😄 It would be good if the viewer automatically cropped to the data.

(I have currently only tested this inside of glue (see glue-viz/glue#1512))

**Comment by nmearl** [comment]
Hmm, strange, it should! The bounds are set by the data limits (with some buffer space) at plot creation time. Does the data have a mask at all?

**Comment by Cadair** [comment]
No mask. This is the data: http://data.sunpy.org/sunkit-sst/CRISP_LXY_Cube.fits.gz

**Comment by nmearl** [comment]
Do you have a custom loader for this data? Also, could you give it a shot with the latest changes?

**Comment by Cadair** [comment]
@nmearl no custom loader, just opened it with Glue. I will give it a try when I get some time, which may not be soon.

**Comment by SaOgaz** [comment]
I get a similar problem of this when I open a JWST file (view is fine here), and then open an additional and click on one of the extensions in that file (view does not re-zoom).
