### ISSUE TITLE
changed_units listener not correctly updating the dispersion slider 

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/specviz#382]
It appears that the listener `specviz_dispatch.changed_units.emit` is not updating the dispersion slider when the units are changed.  This manifests as the green bar going to the far left and the axes "not scaling properly".

cc @brechmos-stsci

**Comment by nmearl** [comment]
This is fixed in #384. However, there is still no way for a user to change the unit information in SpecViz and have it propagate back to CubeViz.
