### ISSUE TITLE
CollapseCube button throws an error

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/specviz#389]
When I click on the 'Collapse Cube' button on the specviz toolbar, it throws an error
```
  File "/Users/crjones/Documents/DATB/cubeviz/specviz/specviz/third_party/glue/plugins.py", line 105, in open_collapse_cube
    self.layout._open_dialog('Collapse Cube', None)
AttributeError: 'NoneType' object has no attribute '_open_dialog'
```

I am looking in to it, but @nmearl if you can suggest a fix that would be great. 

@kassin

**Comment by nmearl** [comment]
This is because your current cubeviz installation does not have spacetelescope/cubeviz#370.
