### ISSUE TITLE
Specviz no longer responds to flux unit changes through dispatch (in Cubeviz)

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/specviz#392]
A bisect seems to point to this commit: https://github.com/spacetelescope/specviz/commit/093b1569ec3b21191086840b047e574dc0220202

![image](https://user-images.githubusercontent.com/2458487/38565787-318619e4-3cb0-11e8-8683-1d4ceecb3f55.png)

**Comment by nmearl** [comment]
Is there an error is the terminal?

**Comment by drdavella** [comment]
No, the displayed data units were not updated. If the user selected a different operation (e.g. median), then the data would be updated, but no units would be displayed after that.

So in short, I'm not sure it ever worked exactly right, but it now works even "less right" than it did before. Once this is fixed we can test this interaction on the cubeviz side, although ideally specviz could provide some unit tests as well.

**Comment by nmearl** [comment]
Is this fixed with @robelgeda's unit fix in cubeviz?
