### ISSUE TITLE
Release specviz on PyPI

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/specviz#404]
It would be good to have releases of specviz on PyPI since users who don't use conda might still want to use specviz (and PyPI is considered the official repository of Python package releases). For glue I don't list PyQt in ``install_requires`` but instead have a hard-check in ``setup.py``:

https://github.com/glue-viz/glue/blob/master/setup.py#L76

I think this is the safest approach as it ensures people get a proper error message if Qt is not installed.

**Comment by javerbukh** [comment]
Always do releases on PyPI.
