### ISSUE TITLE
Re-implement layer arithmetic

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#412]
- Mimic Tom's implementation?

**Comment by mfixstsci** [comment]
Went ahead and hooked up the arithmetic UI to SpecViz by creating a new plugin and button. @robelgeda and I followed the same framework that the rest of SpecViz when you add a plugin to the main tool bar. 

Now all we need to do is pass the Spectrum1d objects that are loaded into the session and pass them to specviz and then write out a corresponding spectrum1d object with the arithmetic results. @astrofrog, when you were developing with the arithmetic editor for glue, how did you avoid the users from injecting python that could be harmful, i.e. deleting files/filesystems.

<img width="1278" alt="arithmetic_plugin" src="https://user-images.githubusercontent.com/13122795/47569985-fd70f300-d902-11e8-8a36-237fe30c3ef5.png">

**Comment by javerbukh** [comment]
In master with tests, documentation, and has been user tested.
