### ISSUE TITLE
Re-implement line lists

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#413]
- Redo events to be signal/slots
- Ensure compatibility with the new plot structure

**Comment by javerbukh** [comment]
@ibusko @nmearl Add what existed in old SpecViz into this refactor.

**Comment by eteq** [comment]
A bit more on this:  This issue is specifically about *only* moving the old functionality into specviz.

A separate question is whether some of this should be moved to specutils (and then specviz would be updated to use that).  See astropy/specutils#364 for discussion on that topic.

**Comment by nmearl** [comment]
Most of this currently is simply rendering a list of lines on a particular plot and perhaps providing some level of interaction. I'm not quite sure which part should live in specutils, unless you mean to store the line list database there.
