### ISSUE TITLE
Re-implement spectral fitting

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#414]
- Create new `ListModel` to contain parameter items.
- (Astropy) implement scipy's curve fit as an astropy fitter to provide parameter errors
- Astropy compound model arithmetic

**Comment by brechmos-stsci** [comment]
For proper use, this will probably require https://github.com/astropy/specutils/pull/360 be merged and then specutils released.

**Comment by eteq** [comment]
Re-tagged high priority because we (@hcferguson , @nluetzge , @gderosa2004) realized it's necessary for most of the background subtraction, which is necessary for analysis
