### ISSUE TITLE
How to ingest user-defined YAML files?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#43]
Currently, `pyfocal` automatically picks up YAML files from `interfaces/default_loaders/` package directory. But what if a user has his/her own `my_weird_fits_format.yaml` definition, then where does it go so that `pyfocal` also picks it up?

It would be undesirable to have user put it in the installation directory (i.e., in `site-packages`). A more logical place is to have `pyfocal` automatically look in `~/.pyfocal/` directory prior to running the GUI, similar to what Ginga is doing for its user configurations and custom plugins.

If `pyfocal` can already do this, then it is just a matter of documentation. Otherwise, this is a new feature that needs to be implemented.

**Comment by nmearl** [comment]
The plan was to use a use-accessible directory like `~/.pyfocal/`. It does not currently look in that directory, but it's just a matter of adding it in addition to `interfaces/default_loaders`.

**Comment by pllim** [comment]
:+1:

**Comment by pllim** [comment]
From the sprint tag-up, users also want to look in the current working directory.

**Comment by nmearl** [comment]
Added searching `~/.pyfocal`, and updated documentation to reflect this in f625cf8e0f362670c894486d4842081090e2a09d. Will try to include looking current directory.

**Comment by pllim** [comment]
Gisella reported that Pyfocal couldn't find her custom YAML file in `~/.pyfocal` last week. Not sure if that is still a problem for her or not.

**Comment by pllim** [comment]
I just tested this and looks like any custom YAML in `~/.specviz` is being ignored.
```python
Traceback (most recent call last):
  File ".../bin/specviz", line 9, in <module>
    load_entry_point('specviz==0.1.0a1.dev228', 'console_scripts', 'specviz')()
  File ".../setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 547, in load_entry_point
    
  File ".../setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 2719, in load_entry_point
    
  File ".../setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 2379, in load
    
  File ".../setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 2385, in resolve
    
  File ".../specviz-0.1.0a1.dev228-py2.7.egg/specviz/app.py", line 14, in <module>
    from .ui.controller import Controller
  File ".../specviz-0.1.0a1.dev228-py2.7.egg/specviz/ui/controller.py", line 14, in <module>
    from ..interfaces.registries import loader_registry
  File ".../specviz-0.1.0a1.dev228-py2.7.egg/specviz/interfaces/registries.py", line 70, in <module>
    loader_registry = CustomLoaderRegistry()
  File ".../specviz-0.1.0a1.dev228-py2.7.egg/specviz/interfaces/registries.py", line 32, in __init__
    custom_loader = yaml.load(open(f_path, 'r'))
IOError: [Errno 2] No such file or directory: u'.../specviz-0.1.0a1.dev228-py2.7.egg/specviz/interfaces/default_loaders/my_yummy_yam.yaml'
```

Also, looks like the code does not look in current working directory (`./`) yet.

**Comment by nmearl** [comment]
Fixed looking in `~/.specviz` in a9034ec664374161065c3ad87b9e2d499bb8d6ec.

**Comment by pllim** [comment]
For documentation purpose, if a user has the same YAML file in both `~/.specviz` and software package, which one has priority?

**Comment by nmearl** [comment]
Hmm, the loader makes no assumptions about the *content*. That is, it's possible to have duplicates. We can require that the name be unique, or else the user file is used?

**Comment by pllim** [comment]
> We can require that the name be unique, or else the user file is used?

:+1: Sounds good. Giving priority to user file makes sense.

**Comment by pllim** [comment]
I can confirm that `~/.specviz` works now -- FYI @gderosa2004
