### ISSUE TITLE
Don't join lines in spectrum plot across NaN values

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/specviz#443]
NaN values in spectra should appear as gaps in the spectrum, and we shouldn't 'jump' across the gap with a line, otherwise there will be this kind of artifact (green line)

<img width="557" alt="screen shot 2018-08-17 at 14 01 44" src="https://user-images.githubusercontent.com/314716/44267465-39624a80-a226-11e8-8ade-256f866444eb.png">

This is important for showing spectral subsets made in glue, but more generically even when reading in spectra with NaN values from files.

**Comment by nmearl** [comment]
This is a simple fix, and I'll get right on it.

**Comment by astrofrog** [comment]
Fixed in https://github.com/spacetelescope/specviz/pull/441 - thanks @nmearl!
