### ISSUE TITLE
ListView Checking/Unchecking Behavior

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/specviz#449]
Nick and I had a short discussion about the following behavior.
Given two datas with incompatible units (data1 and data2):

1. Select and check data1.
2. Uncheck data1. (Note `data1` still remains selected)
3. Check `data2`. 

At this point `data1` is still selected even though it is disabled.

**Comment by javerbukh** [comment]
@robelgeda Would that code automatically select the data if the box is checked? Because that would be a lot more intuitive.

**Comment by robelgeda** [comment]
I agree it is the most intuitive but the main reason we uncoupled the selection and checking is because we want the user to check multiple boxes without losing thier current selection. One controls which data is viewed the other sets the primary data item. @nmearl

**Comment by javerbukh** [comment]
If there is only one box checked, can that one be selected automatically? Also, if you select a box that is not checked, should it be checked automatically?

**Comment by robelgeda** [comment]
That works, I guess we have to ask the testers at some point what makes the most sense.

**Comment by nmearl** [comment]
This should be solved in the latest dev.
