### ISSUE TITLE
Cannot read ASCII file

### ISSUE THREAD

**Issue by XinchengTan** [spacetelescope/specviz#454]
Hi, 

I'm trying to open an ACSII file in specviz, but I got the following error:

### Error: Incompatible loader for selected data: ASCII (*.txt *.dat) because 'Row' object has no attribute 'unit'.

I wonder what is the expected file format? I saved the ascii file in a text file using astropy.table.write that looks like the following:
[tread0.txt](https://github.com/spacetelescope/specviz/files/2454276/tread0.txt)

Did I do anything wrong when creating the ASCII file? I'd appreciate any suggestion on how to get specviz work.

**Comment by nmearl** [comment]
Thanks for the report @XinchengTan. Can you tell me which version of specviz you're using?

**Comment by XinchengTan** [comment]
Hi, it's 0.5.0, on Mac.

**Comment by ibusko** [comment]
Looks like the data file doesn't hold a recognizable spectrum. The columns are labelled as if their units are 'secs' and 'cm/sec'. The file also doesn't conform to the ECSV standard, the only ASCII format supported for now in specviz.

**Comment by ibusko** [comment]
I think it can be closed. Besides, this is from version 0.5.0, which has a differenrt mechanism (I believe) to associate particular loaders to particular file types and contents. On the other hand, maybe we should think a bit on how the new code is going to behave when presented to these wacko files. It uses both "custom" loaders (as defined by specviz itself) as well as specutils-supplied loaders. So the error message may come from either package, depending on the file details.

**Comment by gderosa2004** [comment]
Users will have generic ascii files (not escv format). Do we really want to exclude the majority of the formats around? I think we should have a generic loader that tests for number of columns and assigns 1--> wavelength, 2--> flux, 3--> (if present) error.

**Comment by javerbukh** [comment]
Discussion continued on #502 and #503.
