### ISSUE TITLE
Get Example Loadable Data for Internal Testing

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/specviz#462]
ASCII; FITS: COS, STIS, WFC3/GRISM; WCS

**Comment by gderosa2004** [comment]
It looks like there is already a folder with test data collected from a variety of users [https://github.com/spacetelescope/specviz/wiki/Test-Data](url). I think it would be better to restrict the sample for the moment. I have prepared 4 simple spectra that are ready to be updloaded. @javerbukh do you prefer central storage, or box, or anything else?

**Comment by javerbukh** [comment]
Thats a good question, could you reiterate it at the tag-up today or on slack?

**Comment by gderosa2004** [comment]
Test data are contained in here: /astro/3/jwst_da_sprint_testdata/SpecViz/testdata_201810

example_stis.fits 	STIS spectrum, GD71 (Star)
example_cos.fits 	COS spectrum, NGC5548 (AGN)
example.ascii 		UV spectrum, NGC5548 (AGN)
example_generic.fits 	test spectrum, generic fits file

Will increase the sample if needed.

**Comment by gderosa2004** [comment]
Data are also available in box: https://stsci.app.box.com/folder/56430948756

**Comment by javerbukh** [comment]
More test data from Ivo: `/eng/ssb/busko/tmp/combined_13330_G130M_v40_bin4.fits` of type HST/COS

**Comment by gderosa2004** [comment]
@javerbukh @ibusko the combined*.fits spectrum is mine, it's slightly manipulated and not standard calCOS output. I think it would be better to use the standard cos output currently in the testdata folder

**Comment by gderosa2004** [comment]
Test data have been updated both on central storage (/astro/3/jwst_da_sprint_testdata/SpecViz/testdata_201810) and box (https://stsci.box.com/s/zz2vgbreuzhjtel0d5u96r30oofolod7):

STIS_FUV.fits 	STIS FUV/MAMA spectrum, GD71 (Star)
STIS_NUV.fits 	STIS NUV/MAMA spectrum, GD71 (Star)
STIS_CCD.fits 	STIS optical spectrum, GD71 (Star)
COS_FUV.fits 	COS FUV spectrum, NGC5548 (AGN)
COS_NUV.fits 	COS NUV spectrum, GD71 (Star)
example_generic.fits 	test spectrum, generic fits file

**Comment by SaOgaz** [comment]
@gderosa2004 I don't see the ascii file that's supposed to be in  /astro/3/jwst_da_sprint_testdata/SpecViz/testdata_201810, is it still there?

**Comment by gderosa2004** [comment]
@SaOgaz Updated the folder with .ecsv and .txt examples. Let me know if you need anything else

**Comment by hcferguson** [comment]
Most critical need is still level 2 & 3 output products for *all* JWST spectroscopic modes that produce 1-D extracted spectra. I think we haven't tested yet NIRISS and NIRCam WFSS and NIRSpec FS.

**Comment by SaOgaz** [comment]
JWST data is being covered in separate issues, so closing this issue.  If we still need to do something with other data types I think we should open a new more descriptive issues.
