### ISSUE TITLE
Default ROI size should not be the extent of the spectrum

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/specviz#475]
The default ROI size should be maybe 2/3 of the spectrum that is actually showing on the screen. Assumably the person will zoom in on the area of the spectrum on which they are interested, and then click "add new roi".

**Comment by gderosa2004** [comment]
I think it might be even smaller than 2/3 of the visualized spectrum. I think it is more intuitive to create a small standard ROI with visible limits and have the users modify it. I think that zooming in on an area to create an ROI is counter intuitive.

**Comment by brechmos-stsci** [comment]
I am suggesting that the "add roi" creates a region that is visible on the spectrum that is currently showing in the window no matter the zoom level. Which, unless I am mis-understanding, is the same idea as "with visible limits".  Right?

**Comment by gderosa2004** [comment]
Correct

**Comment by nmearl** [comment]
SpecViz _should_ already be doing this, [as seen here](https://github.com/spacetelescope/specviz/blob/master/specviz/widgets/plotting.py#L487) in the code. It should be initializing the roi as the central 1/4 of the spectrum.

**Comment by gderosa2004** [comment]
@nmearl The initialized ROI is currently larger than the spectrum. Is it a problem with the loaders?

**Comment by brechmos-stsci** [comment]
I am looking at this right now

**Comment by gderosa2004** [comment]
@brechmos-stsci If I use another spectrum (example_generic.fits, available in: /astro/3/jwst_da_sprint_testdata/SpecViz/testdata_201810 ) the ROI is correctly set to 1/4 of the wavelength range.

**Comment by brechmos-stsci** [comment]
@gderosa2004 and @nluetzge I loaded the example_generic.fits file and zoomed in. For example:
![image](https://user-images.githubusercontent.com/18348847/47440041-71808f00-d77b-11e8-93c5-f0863bfb2daf.png)

When I click "Add Region" I get:
![image](https://user-images.githubusercontent.com/18348847/47440091-84935f00-d77b-11e8-8ef9-dcc3b239dfac.png)

And when I zoom out:
![image](https://user-images.githubusercontent.com/18348847/47440204-b0aee000-d77b-11e8-8cf2-9c3c7ff21791.png)

So, with this dataset the ROI appears to be added to span more of the spectrum than just a 1/4.  I would expect the new ROI to be some portion of just the zoomed in spectrum.  So, still looking.

**Comment by gderosa2004** [comment]
If you create a new ROI without zooming in though, you get this:
<img width="971" alt="screen shot 2018-10-24 at 11 35 39 am" src="https://user-images.githubusercontent.com/15363065/47442820-0934ac00-d781-11e8-9208-d219cc04b554.png">

The area is like 1/3 of the spectrum. From my tests, this happens only with this spectrum.

**Comment by nluetzge** [comment]
Yes I can confirm that. It must be some setting specific to that file that set the ROI size...

**Comment by brechmos-stsci** [comment]
I believe I fixed it. PR coming shortly.
