### ISSUE TITLE
Smoothing fails when trying it a second time

### ISSUE THREAD

**Issue by nluetzge** [spacetelescope/specviz#481]
Smoothing a spectrum the first time, works fine. But when I try to smooth it a second time (click again on the spectrum on the left and the hit the smoothing button) the dialog window looks like this and it won't let me click anything on it.
![screen shot 2018-10-24 at 11 49 46 am](https://user-images.githubusercontent.com/24398824/47443978-721d2380-d783-11e8-913d-f9a8d1962db2.png)
That happens even if I delete the first smoothing spectrum.

**Comment by gderosa2004** [comment]
Confirm, same issue here

**Comment by brechmos-stsci** [comment]
I am currently looking at this...

**Comment by brechmos-stsci** [comment]
This will be fixed by PR https://github.com/spacetelescope/specviz/pull/498
