### ISSUE TITLE
Decide on the idiom to use for spectral loaders

### ISSUE THREAD

**Issue by eteq** [spacetelescope/specviz#485]
The "new" specviz presents an opportunity to consider how we are instructing users to provide loaders.  The "old" specviz essentially created a YAML-based file-definition format and asked users to drop the YAML files in a specific place, and there was (or was planned? I'm not sure if it was implemented although @ibusko or @nmearl probably know) a wizard that generated those YAML files in the GUI (see https://specviz.readthedocs.io/en/v0.5.0/custom_loaders.html).

At the time we did not have the `specutils` loader machinery, though (https://specutils.readthedocs.io/en/latest/custom_loading.html).  That's a more standardized/expressive/succinct way to write loaders.  You can see several already exist here: https://github.com/astropy/specutils/tree/master/specutils/io/default_loaders .

So I would advocate for an idiom that is closer to `specutils` as well as `mosviz`: tell users to provide custom loaders that are of the sort `specutils` expects, but in the path specviz previously had the custom YAML files. Then the specutils file loader should ask the user which *kind* of e.g. fits file they are loading, and triggers the appropriate custom loader.  That way we can support the wide breadth of spectral formats out there, but still have something that users can transfer over trivially to a more notebook- or python script-based `specutils` workflow.

cc @nluetzge @gderosa2004 @brechmos-stsci @javerbukh

**Comment by ibusko** [comment]
The wizard code for v.0.5.x lives here: [https://github.com/spacetelescope/specviz/blob/v.0.5.x/specviz/widgets/wizard.py](url) 

It would basically generate, from GUI inputs by the user, the yaml file that would instruct the generic reader to access the particular spectral file. The yaml file could be saved for speedier further use on the same type of file. As far as I recall, the wizard even provided a preview of the spectrum as a simple plot inside the wizard window itself.

**Comment by nluetzge** [comment]
I'm very much in favor of that idea @eteq! I always hated YAML files. And if somebody is not very handy with python I doubt that person would by chance be very handy with YAML ... It would teach people how to write loaders in Python and its similar to what MOSViz is doing which I think is great.

**Comment by gderosa2004** [comment]
@eteq I like this idea a lot! Easy for the users, similar to the other tools, usable in other workflows.

**Comment by javerbukh** [comment]
Continued by #510.
