### ISSUE TITLE
Smoothing GUI popup has extra button

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/specviz#496]
It appears the current smoothing GUI popup has an extra button and something is blocking the ability to click on the "Cancel" button.  (But I can click on the red-ball to close the smoothing GUI popup).

![image](https://user-images.githubusercontent.com/18348847/47650153-ba5a8e00-db55-11e8-8372-04153a549eb1.png)

**Comment by nluetzge** [comment]
@brechmos-stsci I already reported this in issue #481

**Comment by brechmos-stsci** [comment]
Argh, sorry, didn't see that!! :/  Closing this one.
