### ISSUE TITLE
ECSV support

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#502]
This issue is to open a discussion on how to implement support for ECSV-formatted input. The question is whether this can be made general enough that with minimal restrictions lots of different files might be read. For example:

- Try to infer from the units which column is which:

Problem: will fail to distinguish flux from uncertainty.

Solution: Assume the flux column always comes before the uncertainty column. 

With this restriction, it seems like one could read in pretty arbitrary ECSV files. But it would require adding the logic to check for spectral equivalencies or spectral_density equivalencies as part of the reader. 

This kind of logic might also work for ASDF. 

Of course it would throw an error if the units don't make sense. Or, better, pop the user into a wizard with the problem areas highlighted.

**Comment by nmearl** [comment]
It should be noted that there already is an ecsv loader, but it is quite strict.
