### ISSUE TITLE
Plan for New File Loader Wizard

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/specviz#510]
This is a continuation of #416 and all discussion of Loader Wizard changes will happen here.

**Comment by javerbukh** [comment]
1. Templates made to load a certain kind of file and how templates map to dictionary that is being output
2. New way of saving python template files. Update UI to reflect that python templates are used instead of YAML, and that a copy of those templates is always saved in .specutils. If a user is going to overwrite a filename, create dialog to warn them first. Decide what kind of button presses makes the most sense (OK, SAVE, SAVE AS, CANCEL, etc.).
3. Determine if JWST spectrum files contain WCS as opposed to dispersion arrays.
4. Implement WCS loading
5. ASDF loader (might be differed until after the October 2018 sprint)

**Comment by drdavella** [comment]
Related issue in specutils: https://github.com/astropy/specutils/issues/370

**Comment by SaOgaz** [comment]
Maybe this is better as an in person conversation, but what assumptions do we want to make about a potential ascii input as far as formatting?  Was planning on using astropy tables to read in the file, and I could see having a loader builder that could pass on any of the astropy Table pre-set formats through the wizard...

**Comment by hcferguson** [comment]
@sogaz happy to chat about this.

**Comment by SaOgaz** [comment]
@javerbukh @hcferguson , are we good to close this issue now?

**Comment by hcferguson** [comment]
@hcferguson Yes, I think this can be closed.

**Comment by SaOgaz** [comment]
I'm going to be opening new separate issues for the file loader wizard, so closing this one.
