### ISSUE TITLE
Develop the "getting started" section of the specviz docs

### ISSUE THREAD

**Issue by eteq** [spacetelescope/specviz#514]
#512 added a rough outline of the docs, including a "fake" getting started section.  That section should actually be populated, showing a few highlights of what specviz can do.  The key is to not overload the user with info here, but rather pick some highlights and reference more comprehensive pages later on.

For the content I would image something like load a simple (no-wizard) spectrum, do a quick background subtraction, measure something about a line.  That seems like the simplest "do something useful" steps to me... But perhaps @hcferguson, @nluetzge, or @gderosa2004 have some additional/alternate thoughts here?

**Comment by hcferguson** [comment]
Given the discussions....seems like a section on "Data Formats" or "Data Loaders" might be what I would expect to find. It would outline the supported data formats and include subsections on "The loader wizard" and "building custom loaders"

**Comment by eteq** [comment]
Ah, so what I was imagining in #512 is that at least the custom loader/widget discussion would be a *separate* section that would let the page drill down deeper.  The previous docs I found to be quickly a deep-dive, so this specific issue was meant to focus on the "I just want to see a few things specviz does".  Will clarify that in #512. But perhaps the wizard is important enough to at least mention at the outset, @hcferguson ?

**Comment by hcferguson** [comment]
I would mention the wizard early on and also mention a few supported formats.
