### ISSUE TITLE
Model saving

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/specviz#516]

**Comment by brechmos-stsci** [comment]
Ah, didn't realize I was assigned this. I won't be able to get to this today but maybe early next week.

@javerbukh or @hcferguson or @nmearl  Could someone add a few more details to the ticket?  Is this for saving the fitted models from line fitting?  Either way, is there an expected file format to use?

**Comment by hcferguson** [comment]
@ibusko had worked out a way to save models in the earlier specviz. But seems like this is a thing that should go in SpecUtils, and then just be called from SpecViz?

**Comment by ibusko** [comment]
The code to read and save a model is in files specviz/interfaces/model_io/ *.py and  specviz/plugins/model_fitting_plugin.py in v.0.5.x, starting at line 570.

It can write a model in a yaml file, or as a .py script that can be used in notebooks and such. The yaml file can be read back as a fully operational model as well.

**Comment by brechmos-stsci** [comment]
To be clear, based on the discussion between @eteq @nmearl and @hcferguson, I believe the decision was to put the saving into specviz, not specutils, right?

**Comment by hcferguson** [comment]
Yes, that is my understanding of the discussion.

Just to record my dissent: I think we have diverging philosophies....I suspect @nmearl and @eteq lean toward a more minimal SpecUtils. I lean toward making the SpecViz as lightweight as possible, just exposing SpecUtils functions with a GUI layer. Seems to me with that philosophy, this would go in SpecUtils. I'm happy to defer to @nmearl and @eteq though.

**Comment by brechmos-stsci** [comment]
I would tend to agree, in principle. All GUI stuff goes in specviz. All non-GUI stuff goes in specutils. But, I will implement in specviz next week.

**Comment by brechmos-stsci** [comment]
There are two methods to load and save in the old specviz. One saves and loads to Python and one saves and loads to yaml.  I assume both are wanted in the new code base?

**Comment by ibusko** [comment]
Afaik, loading a pyhton script was forbidden for security reasons. That's why we have the save/read to/from yaml file. So these can be used to save data in between sessions. Python is used for export only.

**Comment by nmearl** [comment]
Since we're moving away from using YAML, I would suggest just serializing/deserializing to disk the specviz-created compound model using pickle or similar.

**Comment by drdavella** [comment]
Or ASDF? 😉 

Actually if it's just an Astropy model that should be straightforward.

**Comment by hcferguson** [comment]
If we are going to serialize/deserialize then we should use YAML. Or ASDF if we need to support binary (but I don't think we do here). The advantage over pickle is human readability and edibility.

**Comment by brechmos-stsci** [comment]
@drdavella and I were just looking at this. Given that the *baseline* functionality is to be able to save and load models, then Pickle would be the fastest way to have something implemented in the next day or so.  

So, if this is something wanted this week, then doing Pickle is probably the best option. Then we can add an issue to be able to do "Save As" to python, yaml or asdf, but later on.

The wild card in this is that neither @drdavella, nor I, know how the GUI part of the saving was happening in the old code.

**Comment by ibusko** [comment]
@brechmos-stsci I may not have understood the issue correctly, but the old read/save code didn't deal with GUIs at all, as far as I recall. The model was saved in a format independent of the code itself. Well, I guess with pickling parts of the GUI could also be saved? 

We just have to remember that pickling should be a temporary solution, because it breaks when the python version changes (if I recall correctly).

**Comment by nmearl** [comment]
@brechmos-stsci You'll want to add the saving and loading functionality to the model editor plugin. Technically, you'll only need to interact with the internal data model, and only with the astropy compound model.

That is:

```python
# For any currently selected data item, check to see if that data item contains an astropy model
if isinstance(self.hub.data_item, ModelDataItem):
    # If so, run the evaluation method which looks at the user-provided equation and generates an
    # astropy compound model accordingly, scrapping all current ui parameter values.
    compound_model = self.hub.data_item.model_editor_model.evaluate()

    # Store the current equation text, since it'd be much easier than having to parse the operator tree
    compound_model._equation = self.hub.data_item.model_editor_model.equation
```

Then, it's a matter of pickling the compound model. Upon loading an unpickled compound model into the ui, simply add the sub models to the compound model to the internal data model, and the ui will take care of itself:

```python
for sub_mod in unpickled_compound_model:
    self.hub.data_item.model_editor_model.add_model(sub_mod)

# Restore the equation to the ui
self.hub.data_item.model_editor_model.equation = unpickled_compound_model._equation
```

The terminology gets a little weird because we're dealing with both the astorpy _model_ and the qt _model_ internally.
