### ISSUE TITLE
line lists in "old" SpecViz don't play nicely with spectra that are redshifted

### ISSUE THREAD

**Issue by kassin** [spacetelescope/specviz#518]
When I read in a spectrum of a redshifted galaxy, the line list plug-in only lets me choose lines in the wavelengths which the spectrum has.  So, if the galaxy has an H-alpha line (rest 6563A) at 1 microns (=10000A)  in the observed frame (which the spectrum shows), the line list plug-in doesn't offer the H-alpha line as an option.

@ibusko @apmarston

**Comment by ibusko** [comment]
You can enter the range of wavelengths that it reads from the line list, using the wavelength range dialog that shows up when you pick a line list in the drop down menu. The dialog is initialized with the wavelength range actually spanned by the data, but you can make the range anyway you like. Isn't that feature working for you?

**Comment by kassin** [comment]
Yes!  Got it.  Works nicely.  Thank you!!
