### ISSUE TITLE
flux units should not be auto-converted to SI prefixes by pyqtgraph

### ISSUE THREAD

**Issue by eteq** [spacetelescope/specviz#522]
Most of the context for this issue is in #521, https://github.com/spacetelescope/specviz/pull/480#issuecomment-435141361 and https://github.com/spacetelescope/specviz/pull/480#issuecomment-435163125 .  Essentially the problem is this: if I load in a spectrum with flux of `array([4.0115904e-14, 2.7294973e-14, 2.5229817e-14, ..., 2.7819518e-14,
       1.6174598e-13, 1.6174598e-13], dtype=float32)`  and units of `'erg /s /cm**2 /angstrom'`, spcviz pops up with flux units of femto-erg /s /cm**2 /angstrom (a unit astronomers do not use, even though it is technically a valid unit).  That's not desirable behavior, because it hides from the user what the "true" values of the spectrum are.  Given one of specviz's use cases as a "quick look" tool, it's very important the user sees exactly what is in the file they load.

Of course, they should have the *option* to change it to another unit, which is what #480 enables.  That way they can *ask* to use femto-ergs. 

If I understand right from @nmearl this is a pretty trivial change of just turning off the automatic pyqtgraph auto-SI setting? (I scoped it 1 under that assumption)

**Comment by eteq** [comment]
@hcferguson - do you agree with the conclusion I came to here?  In https://github.com/spacetelescope/specviz/pull/480#issuecomment-435141361 I thought you did, but in https://github.com/spacetelescope/specviz/pull/480#issuecomment-435188535 it looks like not.

I still content it's confusing because it's mixing two "units" systems (I think? Or does the auto-si thingie actually defer its conversions to the spectrum's units?)  and hides from the user what their actual data is...

**Comment by nmearl** [comment]
What do you mean by "defer its conversions to the spectrum's units"?

**Comment by nmearl** [comment]
To expound on what I said before, there's no "auto-converting" happening (insofar as "converting" refers to converting from one unit to another through some understanding of what "units" are). pyqtgraph has no concept of units, it only understands powers of ten. If a unit string has been defined, it will see `10e3 x` and say "Oh, well, this could be better show as `1 kx`", with no regard to what the unit actually is. This _only_ applies to the representation of the points on the graph, and in no other case is this `kx` accessible or usable.

**Comment by hcferguson** [comment]
I agree that if this is only occurring on the plots, then it's better for it not to occur. Also femto-erg won't be familiar to most astronomers (while mJy would be). So if we can turn the auto-converting off fstat would be better.

**Comment by brechmos-stsci** [comment]
So as part of turning off the auto-convert display of the units on the graph, then we should also add in uJy and mJy to the list of available units to which we can convert. (Last I saw https://github.com/spacetelescope/specviz/pull/480 will only do Jy)

**Comment by hcferguson** [comment]
Yes.

**Comment by gderosa2004** [comment]
I agree with both @eteq and @hcferguson, femto erg would be highly confusing for 90% of the users.

**Comment by javerbukh** [comment]
@brechmos-stsci I see this come up repeatedly and I bring this up every time, as far as I know, you can get all of the prefixes or none of them. This is what all of them would look like:
![screen shot 2018-11-01 at 2 50 22 pm](https://user-images.githubusercontent.com/7179333/47918173-2274e100-de82-11e8-8cb8-a090ca95d541.png)

**Comment by hcferguson** [comment]
@javerbukh Is it getting that list from Astropy somehow?

**Comment by hcferguson** [comment]
I'm not sure how find_equivalent_units is supposed to work, but I think maybe use of this might be related to the problem with some of the options disappearing. When I try running it, all I get is a list of the Jy equivalents, and don't see things like erg cm-2 s-1 AA-1 or erg cm-2 s-1 Hz-1.

**Comment by javerbukh** [comment]
@hcferguson Are you using the latest version of master? Options no longer disappear. There are ways to find more equivalent flux units(such as `Spectral (Doppler) equivalencies` and `Brightness Temperature / Surface Brightness Equivalency`, but is that an issue that is of high importance to this sprint, or is it something that we can come back to afterwards?

**Comment by hcferguson** [comment]
@javerbukh I think so. But I can't really get it to do anything except crash, so my installation may still have some problems.

**Comment by brechmos-stsci** [comment]
In Cubeviz we specifically list out the units, in part, we can convert to.  I don't know that having YottaJansky is going to be wanted, but that would be interesting to see data acquired in that range. :)

**Comment by hcferguson** [comment]
@javerbukh @brechmos-stsci I think the basic issue of not converting to SI prefixes has been addressed, right? So close this and track other units related issues elsewhere?

**Comment by hcferguson** [comment]
Closing. Seems like it's fixed at least in the version I'm using today v0.6.dev01898.
