### ISSUE TITLE
dark_mode

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#526]
In dark mode the plots were coming out black on black (couldn't see the spectrum).

**Comment by gderosa2004** [comment]
@hcferguson is it the "color theme"? If I try to select dark nothing happens and I get an error: 
`ERROR:root:No dark style installed.
`
@nluetzge gets the same behavior.

**Comment by nluetzge** [comment]
@nmearl I think he means this:
![screen shot 2018-11-02 at 2 36 07 pm](https://user-images.githubusercontent.com/24398824/47934080-b6f43900-deac-11e8-91e2-24b2b82def1d.png)

**Comment by nmearl** [comment]
That's right, it should be non-usable when the user doesn't have the theme installed. Users _can_ install the theme via `pip install git+https://github.com/nmearl/QDarkStyleSheet`, but it's not finished, and shouldn't be considered a top-level feature for release.

**Comment by hcferguson** [comment]
Yeah, that's probably it. I had it left over in an old startup file, so I was getting it as my default theme. When I deleted the startup file, it went back to the default theme.
