### ISSUE TITLE
Docstrings for all classes

### ISSUE THREAD

**Issue by eteq** [spacetelescope/specviz#529]
This is admittedly a relatively minor thing (so I "low-priority"'ed it).  But it falls in the category of "makes things easier for new developers or users who want to hack around a bit": a lot of the core objections in `specviz` don't have docstrings.  While most methods do, the classes themselves do not.  Adding such docstrings provides small bits of context that make it easier to "jump in" on developing specviz without having to go around and ask someone "what does that do?"

**Comment by hcferguson** [comment]
Not sure what the status here...any way to auto check that all classes have docstrings?

**Comment by drdavella** [comment]
It looks like it should be possible. We would need to set up a `flake8` test for code style, which would be a good idea anyway. Then it looks like using the [flake8-docstrings](https://pypi.org/project/flake8-docstrings) plugin would allow us to check for this.
