### ISSUE TITLE
Fix RTD build for specviz

### ISSUE THREAD

**Issue by eteq** [spacetelescope/specviz#530]
Currently the "new specviz" is not building correctly in Readthedocs (see e.g. https://readthedocs.org/projects/specviz/builds/8043550/).

The problem appears to be that it's trying to install using python 2.7, which isn't supported.  But that's weird because both the RTD config page and the `readthedocs.yml` say python 3... more investigation needed.

**Comment by nmearl** [comment]
Am I misunderstanding something? The build log looks like it's failing on a missing `ConfigParser` dependency?

**Comment by eteq** [comment]
@nmearl - yes, because the `ConfigParser` package was renamed `configparser` in python 3.  I suspect the old specviz used py2 to build the docs (maybe you can confirm), and that's no longer possible if there's an `import configparser` instead of `import ConfigParser`. And based on the RTD build log it's using py 2.7 (all the conda packages end in py27).

The thing is, it *should* be building on python 3 based on what I think I've instructed RTD. I don't really get what RTD is using to decide its build process though. Hence the more investigation needed.

**Comment by eteq** [comment]
Oh, I think the trick may have been adding an explicit conda dep in `.rtd-environment.yml`.  Testing now...

**Comment by eteq** [comment]
Yep that looks to have been the trick, *as well as* needing to explicitly install the `sphinx-astropy` package from pip. See https://readthedocs.org/projects/specviz/builds/8057523/
