### ISSUE TITLE
Should the fitter GUI *actually* work on all models?

### ISSUE THREAD

**Issue by eteq** [spacetelescope/specviz#535]
@brechmos-stsci and I were just discussing some implementation issues on the specutils side triggered by the fitter GUI (which @robelgeda has been working on), and it led to a User Experience question I think we need to think about a bit more broadly.

That is: is it really desirable that *all* the different kind of astropy models can be fit to a spectrum?  That was reasonable in the past when we didn't have significant unit restrictions, but is now a bit more awkward because `specutils` is being careful with units in a way that previously wasn't expected of the model-fitting.  While this can be worked around by simply ignoring units and blindly fitting a model, it raises the question of whether that's *desirable*.

More concretely: `specutils` fitting doesn't work with models that have units that don't play well with the spectrum's units.  In `specutils` that's less of a problem than `specviz` because the user has to choose the units anyway.  But in `specviz`'s fitting GUI, it's not as straightforward, and indeed for some complex models it's a pain to get the units right.  So we *could* modify `specutils` fitting to have an option that's essentially `ignore_units`, and just have `specviz` always use that. But then that defeats the whole point of using units in the first place...  So I see a few different ways to resolves this:

1. Only allow the `specviz` gui to fit models that `specutils` recognizes and knows how to set the units for (i.e. polynomials for continuum fitting and gaussian, lorentzian, or voigt for lines). No change in `specutils` required.
2. Implement `ignore_units` in `specutils`, and have `specviz` always use that, completely ignoring units in fitting (i.e., the user has to do it manually).
3. Implement `ignore_units` in specutils, but have `specviz` by *default* not do that - i.e., the first option here, but have a checkbox (or "advanced mode" or similar) that then shows all the models, but doesn't do any unit-checking
4.  Some other possibility I haven't thought of ... 

cc @hcferguson @nluetzge @gderosa2004, as scientist-users who might have opinions on the UX.

**Comment by brechmos-stsci** [comment]
@robelgeda This is related to the discussion we had this morning about how to construct a sub-models with units in an easy way (given that parameters might be spectral axis unit types or flux unit types).

Some discussion with @robelgeda lead to the fact that the parameter estimation might be an easy way to do this as it will figure out the right parameters.  But the parameter estimation is based on knowledge of Const1D, Voigt1D, Gaussian1D and Lorentzian1D models (primarily).  The parameter estimation PR is not quite there, but hopefully very early this week the PR will be ready.

**Comment by nluetzge** [comment]
I think I would go for number 3 and make it very clear which one have unit support an which don't. But I'm also kind of lacking the imagination on how people would do the units "by hand".

**Comment by eteq** [comment]
> But I'm also kind of lacking the imagination on how people would do the units "by hand".

I am also lacking that imagination, @nluetzge, which is why I *also* favor 3 (should have said that above).

**Comment by brechmos-stsci** [comment]
This will tie into https://github.com/astropy/specutils/pull/362 as well

**Comment by robelgeda** [comment]
I also would like to mention the hack I am using to develop. I just convert the flux and spectral values to the displayed units -> convert them to numpy arrays without units -> use astrpy modeling to fit. That way the user can always assume the units of the fitting parameters are always the same units as whats being plotted. I have to use astropy molding in this case because SpecUtils Spectrum1D requires the flux values to have a unit. We could use this if it takes a lot of time to develop the SpecUtils version?

**Comment by robelgeda** [comment]
@eteq : From a coding point of view an important question is how would one know what type of units to use for each parameter of the models? Should we hard-code acceptable units and check if user inputted units are equivalent to the hard-coded ones? If so, I am thinking having a registry of parameters and example units, does that sound like a good solution?

**Comment by hcferguson** [comment]
@eteq I think it's important to have an *option* in `specutils` and `specviz` to ignore units. I would guess this will start out being the most common use case, until spectra start getting distributed with a more standardized treatment of units or until we build the umpteen loaders needed to interpret them. 

So I vote for option (3).

**Comment by eteq** [comment]
@robelgeda 

> I also would like to mention the hack I am using to develop. 

Yeah, that works but it then side-steps all the work that's been put into specutils to develop a spectroscopy-specific API. So what I'm suggesting is that we use the workflow and API idioms from specutils to sort of "inspire" the specviz workflows.  More prosaically, it also means that as the `specutils` implementation improves by e.g. handling uncertainties or smarter ways to guess line parameters, that should be transparently passed onto `specviz`.  That can't happen if you side-step all the specutils machinery.

> how would one know what type of units to use for each parameter of the models? ... If so, I am thinking having a registry of parameters and example units, does that sound like a good solution?

That's what I'm saying above: this is very hard to do right now *generically*, because some models don't have any sensible units. For example, the `Sersic1D` model doesn't make any sense to use in a spectral context, so there's *no* good choice of units.

For those where it *does* make sense, it's a good question whether this should live in `specviz` or `specutils`.  The simplest thing is to do no *validating* in `specviz` but rather catch exceptions when the fit happens - i.e.,  if you pass invalid units into `specutils`, it will raise an exception, which you could then catch, and, say, light up a red box around the offending unit.  The next step more complicated would be a registry like you suggest, @robelgeda, but that has the danger that it has to be kept in sync with the relevant `specutils` functions.  E.g., if the continuum fitting functions in specutils later support a new class, you then have to know to *also* update `specviz` to support that model.

**Comment by eteq** [comment]
FWIW, it looks like we may be quickly converging on option (3) of my original list.

**Comment by gderosa2004** [comment]
@eteq I would like 2 the most, but I can live with option 3

**Comment by eteq** [comment]
@gderosa2004 - just to be clear on that: you actively think units should *not* be supported (which was 2), or you think it's fine but just don't think they should be default? (which would sort of be an option 4 I guess, but basically a minor perturbation on 3)

**Comment by brechmos-stsci** [comment]
So, for my part, I will create an issue and subsequent PR in specutils that will create a flag called `ignore_units` on the `fit_models` method. This will then fit the spectrum to the given model ignoring any units on the given model. 

https://github.com/astropy/specutils/issues/386

(I believe the rest of the work is in specviz)

**Comment by eteq** [comment]
To copy some discussion here that @brechmos-stsci @hcferguson @robelgeda and I had in person: for the version of specviz we want to release this week, it's probably not feasible to get option 3 in, because that requires too much development of the units-parsing in the specviz GUI.  So we are  going to do option 2 for the upcoming release, but keep this issue open to aim for option 3 in the *next* release.
