### ISSUE TITLE
Ideas for demo videos

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#54]
As mentioned in sprint tag-up, a short demo video to link/embed in the documentation would be nice. Going forward, there can be even a series of them, each showcasing a different functionality. We can perhaps list some ideas here for that purpose. Each video should not be longer than a few minutes.

As a start, just a basic video showing how to load a single spectrum, select an emission/absorption line, and then fit a Gaussian to it would be nice.

**Comment by justincely** [comment]
@pllim are you aware of an SSB/STScI video channel anywhere?  Someplace we could host videos like this?  I feel like vimeo or youtube can be a place for these where we can have whole channel devoted to our tools.

**Comment by pllim** [comment]
I don't even know what a Vimeo is. Maybe OPO already has something set up, not sure.

**Comment by pllim** [comment]
Update: I asked OPO. The answer is we cannot use their YouTube channel, which is specifically for outreach to general public. So, we need to set up our own.

**Comment by justincely** [comment]
Thanks for checking - but they had no problem with us setting up our own?  (they seem to be the definitive yes/no on social-media stuff like this)

**Comment by pllim** [comment]
OPO said it would be ideal to have a STScI-wide channel set up and said to inquire with Joel Green.

**Comment by astrofrog** [comment]
cc @groorg1
