### ISSUE TITLE
Model Fitting Parameter Significant Figures

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/specviz#558]
The model fitter displays the values of all fitted parameters on the model fitting side bar. Currently, we format the result to display at most 5 significant figures. How much accuracy dose the user expect? How do we handle model parameter values for dense spectra over short wavebands?
CC: @nmearl @nluetzge @gderosa2004 @hcferguson @eteq

**Comment by hcferguson** [comment]
For the first question, for display on the screen I would say that 4 significant figures is sufficient as long as the user can save results to machine precision when they save the model. 

I don't understand what you are asking in the second question.

**Comment by robelgeda** [comment]
Thanks @hcferguson. Here is an extreme example for the second question:
Suppose the user has data with `Hz` as the spectral axis and the data ranges from 1.9990e15 to 2e15 Hz. In this case we need a higher precision to describe the parameter dealing with the spectral axis. Another example is if the wavelength in in angstroms, say a sharp spike b/w 11150 and 11151 angstroms. I guess a better way of asking is how to deal with high resolution data? Would it be of interest to get more information in these cases?

**Comment by hcferguson** [comment]
@robelgeda I hadn't thought much about the spectral axis. For now I would say 4 significant figures will suffice for JWST use cases. 

For high-resolution ground-based spectra I think 6 would be the highest needed. Down the road, we could add the ability to set precision to a preferences menu or to the "advanced" panel of the fitting to handle such cases. But I would hate to clutter up the JWST outputs for the high-resolution spectroscopy use case.

**Comment by robelgeda** [comment]
Sounds good to me.
