### ISSUE TITLE
Fitter got unexpected keyword argument "maxiter"

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#561]
Tried to fit a Linear1D model to a STIS spectrum and it crashed with the following error log:
```
Traceback (most recent call last):
  File "/Users/hcferguson/software/git-clones/specviz/specviz/plugins/model_editor/model_editor.py", line 403, in _on_fit_clicked
    window=spectral_region, **kwargs)
TypeError: fit_lines() got an unexpected keyword argument 'maxiter'
```
Screenshot of the viewer just before hitting "fit model" attached.

<img width="1186" alt="screen shot 2018-11-16 at 10 00 01 am" src="https://user-images.githubusercontent.com/2261329/48629262-29721800-e987-11e8-82cf-1bb221354023.png">

**Comment by nmearl** [comment]
I can't replicate -- are you using the latest specutils?

**Comment by brechmos-stsci** [comment]
And the latest specutils?

**Comment by hcferguson** [comment]
I'm doing this in specviz, having done a fetch on specutils first. But I'm not sure if specviz is therefore using the latest specutils or not. Probably not, if you aren't reproducing this.

**Comment by hcferguson** [comment]
It was using an older version of specutils. I don't see this error with the current version.
