### ISSUE TITLE
Model editor UI improvements

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/specviz#571]
- [ ] Move model editor toolbar to the top of the widget
- [ ] Move the `Load Models` option out of the `Add Models` dropdown and into its own icon

I'm happy to take this on unless someone else is itching to do it.

**Comment by hcferguson** [comment]
Closing this. Toward the end of the last sprint, @robelgeda made some tweaks to address these two issues. 

We should consider further UI enhancements as part of more comprehensive review & planning for the entire UI/UX.
