### ISSUE TITLE
 loader wizard save/load buttons

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/specviz#591]
We need to update the loader wizard back to having two buttons at the bottom of the wizard, a close (which does nothing) and an open, which will take the generated loader and immediately use it to open the file.

Comment from @hcferguson (because I posted this issue in the wrong repo, haha):

"How about three: "Read Spectrum" and "Save Loader" and "Close Wizard"?

Or "Read", "Save" and "Close" if there isn't enough space.

Regarding "Save" -- it's very confusing to have the loader name be different from the filename, and causes crashes if the module name already exists. I'd suggest just enforcing that the loader name and the filename have to be the same. And testing whether a loader of that name already exists before saving. That will simplify the save dialog for the user, since the file naming part can be automatic."

**Comment by nmearl** [comment]
>  it's very confusing to have the loader name be different from the filename, and causes crashes if the module name already exists.

This has been fixed in the lastest specviz. Save file names are pre-populated with the name of the loader. It also won't let you save two loaders with the same name.
