### ISSUE TITLE
Model editor multiple warnings   

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/specviz#597]
When the selected data to be fitted is a model or if an old model is selected when a new model is created... multiple warning pop up with the same warning.

**Comment by nmearl** [comment]
I think the displayed values in the data drop down of the model plugin should filter based on `PlotDataItem` vs `ModelDataItem`, and only allow selecting the `PlotDataItem`s.

**Comment by robelgeda** [comment]
I agree, I suppose we should use a `QSortFilterProxyModel` but I am not sure how to filter based on type. Is this the right approach or should we just populate the combo in a function and have that function listen for data changed calls?

**Comment by nmearl** [comment]
```python
class FitDataProxyModel(QSortFilterProxyModel):
    def filterAcceptsRow(self, p_int, index):
        data_item = self.sourceModel().data(index, role=Qt.UserRole)

        if isinstance(data_item, ModelDataItem):
            return False

        return super().filterAcceptsRow(p_int, index)
```

And you'd just set the proxy model instead of the real model

```python
proxy_model = FitDataProxyModel(self.hub.model)
self.data_selection_combo.setModel(proxy_model)
```

**Comment by robelgeda** [comment]
neat, thanks! I will self assign. I won't be able to get to this till next week though.
