### ISSUE TITLE
Ability to tweak continuum fitting beyond just setting ROIs

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#603]
While there is now continuum fitting under "operations" it is completely automatic apart from setting  ROIs. But a typical workflow might also involve some experiments with the functional form (e.g. more or fewer spline knots) and more robust fitting.  This issue is to collect ideas about the functionality & user interface. Many of these issues are also relevant to model fitting, so should be addressed in a uniform way, whether or not we have a separate plugin-in or operation for continuum fitting.

Several thoughts to get the ball rolling:

1. Since SpecViz is intended as a GUI tool, at a minimum we should have a way for the user to mark not only regions but individual pixels to exclude. 

2. The most basic robust fitting would have some sort of iterative sigma rejection. That should be in SpecUtils, but SpecViz should then mark the rejected pixels. The user interface should allow the user to control sigma levels and number of iterations.

3. Scikit-learn has some nice robust regression features. It might be worth exploring whether they can be exposed to SpecViz somehow. That would presumably require some kind of connection to then first through SpecUtils and possibly Astropy.

**Comment by brechmos-stsci** [comment]
2. and 3. would be relatively easy to add in to specutils if you wanted to specify the regression features you were interested in...

**Comment by hcferguson** [comment]
@nmearl I'm a bit agnostic on this, but I can see a few advantages to making it separate. It would free us up from having to make everything generic to models and might allow us to make an interface that's clearer to users. For example -- a spline fit is a perfectly good continuum model, but is very messy to present as a parametrized model. Even some kind of iterative smoothing after rejection of features is a valid way of estimating continuum, and that clearly isn't just a use-case of parametrized model fitting.

**Comment by eteq** [comment]
@hcferguson - I think at least part of this is already done: you do the operation step but then can *re-fit* using ROIs et al.

So then one more related perspective here: as I mentioned in #573, I advocated having the concept of a special model that's "the continuum", which would only be special by name. That already gets done in the existing "operation" button, *but* it doesn't do the second part of #573, which is to automatically *use* that continuum for the stats panel.
