### ISSUE TITLE
Should the loader selection dropdown default to "Auto"?

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/specviz#615]
During a previous sprint I introduced a change to require users to explicitly choose a loader before clicking `Open` (see #491). This was to prevent the wrong option from being chosen inadvertently.

However, now that automatic loader selection has been implemented (#527), this no longer seems useful/necessary. Instead, it would make sense for the default to be `Auto`.

**Comment by nmearl** [comment]
Agreed. Auto should be default (I think it is currently as well?)
