### ISSUE TITLE
Units conversion does not update the plot.

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/specviz#625]
When the user selects the units for the wavelength axis and clicks "OK", the plot goes bonkers: it displays no data, and the wavelength axis still has the older units in place. By clicking the "Reset View" button  the plot gets corrected, but any zooming operation performed previously gets lost.

This doesn't happen all the time. I tried to see if there is a pattern like converting from one class of units to another would cause it, but in the same class it would behave correctly, but I didn't see any. (by 'class' I mean wavelength/energy/frequency)

**Comment by nmearl** [comment]
Are you in master? There have been additions to ensure that the plot is correctly reset.

**Comment by ibusko** [comment]
yes, I'm in master.

**Comment by nmearl** [comment]
Which data are you using and what units are you converting to?

**Comment by ibusko** [comment]
I am using a HST COS spectrum that we have been using before:  -H -F combined_13330_G130M_v40_bin4.fits -L HST/COS

It happens with any of the units, apparently, it's just that sometimes the resulting wavelength values are close enough to the old values that the spectrum still shows up in the plot window.

**Comment by ibusko** [comment]
You're right, it was my version of the code that was outdated. I am closing the issue.
