### ISSUE TITLE
ROI doesn't respond to units changes

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/specviz#626]
When a wavelength region other than the full spectral range is selected, and the wavelength axis units are changed, the ROI apparently doesn't respond to the units selection signal. This causes it to display at the old (numerical) position on the X axis, messing up the display.

Also, the region range reporting text at the top left of the plot window doesn't get updated either when X axis units are changed.

**Comment by ibusko** [comment]
In fact, the cause of this seems to be that the region is not responding to the units change.

**Comment by nmearl** [comment]
I'm not seeing this -- the statistics works as expected when changing units. I'm suing the COS_FUV data set.
