### ISSUE TITLE
Spectrum display: default line weights and colors are not good

### ISSUE THREAD

**Issue by kassin** [spacetelescope/specviz#631]
Default line weight should be heavier (by a factor of ~2) and the colors scheme should allow the user to properly view fit.  See the attached screen shot.  The fitted Gaussian and constant are the same color as the background grid (please remove this) and also the same color as the lines around the ROI (please remove these lines too).  Furthermore, the light grey color is hard to see.
![screen shot 2019-01-30 at 2 58 17 pm](https://user-images.githubusercontent.com/11748049/52008835-85850c80-249f-11e9-9ecd-7a2fe726a602.png)

**Comment by nluetzge** [comment]
The line width issue was already attempted here https://github.com/spacetelescope/specviz/pull/505 but then discarded because of performance reasons.

**Comment by kassin** [comment]
Is this a PyQT bug?

**Comment by javerbukh** [comment]
@kassin no. See Nick's comments in #505.

**Comment by kassin** [comment]
More like a "feature" of pyqt.  This is not good for SpecViz at all...

**Comment by nmearl** [comment]
I can verify that enabling `opengl` improves performance drastically (though, slightly less than when width of 1). I will put up a PR and the testers can determine if it's "good enough".

**Comment by SaOgaz** [comment]
To add onto this, we got similar feedback to Susan's (first comment block of the tickets) from @bethanjames during a recent testing session.
