### ISSUE TITLE
Spectrum display ranges do not update correctly when change units

### ISSUE THREAD

**Issue by kassin** [spacetelescope/specviz#632]
When the units are changed on a spectrum and the spectrum is replotted, the ranges shows are incorrect.  These screenshots shows what happens when the wavelength axis is changed from microns to Angstroms.  
![screen shot 2019-01-30 at 3 01 10 pm](https://user-images.githubusercontent.com/11748049/52009110-165be800-24a0-11e9-998f-4c127f781ce4.png)

![screen shot 2019-01-30 at 3 01 22 pm](https://user-images.githubusercontent.com/11748049/52009113-1a880580-24a0-11e9-9efb-5a18a1eb32d2.png)

**Comment by nmearl** [comment]
This actually caused by a different bug (#626): the ROI is not being moved to the new unit range (your ROI is bunched up near 0 in your second image).

The displayed region information is linked to the ROI, and is _technically_ behaving correctly in this case.
