### ISSUE TITLE
Ability to right click data items in list view

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/specviz#641]
The ability to right click data items in the list view which results in a dropdown menu. This may be useful for quick interactions with the data objects such as deleting them. @kassin

**Comment by nmearl** [comment]
We had feedback from the previous specviz version that people weren't aware that items in the list could be right clicked. They preferred the operations on the data items (like deleting data or exporting data) to be visible in the top tool bar. Of course we can revisit this.

**Comment by robelgeda** [comment]
Sounds good, we can close this. I will leave it open for now to serve as a reminder to talk about it sometime in the future.

**Comment by kassin** [comment]
As the product owner, I'd like to leave this issue open for discussion if there is another SpecViz sprint.
