### ISSUE TITLE
Data List View Size 

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/specviz#642]
When SpecViz pops up, the side bar that contains the data list view has a very large width which takes away from the width of the plot widget. Of course the user can resize it but we should have a good default rule to avoid this:

<img width="1283" alt="screen shot 2019-01-31 at 4 48 52 pm" src="https://user-images.githubusercontent.com/10345916/52087723-35c64400-2578-11e9-97d9-2b547f561e83.png">

**Comment by nmearl** [comment]
Strange, there is a default size for the data list view. When I open specviz, it opens at an appropriate size -- will investigate.

**Comment by nmearl** [comment]
Can you check this again? Some tweaks have been made to the size constraints of the ui.

**Comment by robelgeda** [comment]
This is still a problem. Saw it on someone else's 13" MacBook as well.

**Comment by nmearl** [comment]
You were testing with the latest version on master? I went through and fixed the sizing of all three main panels as part of the last cubeviz sprint.

**Comment by robelgeda** [comment]
I believe so, we installed via pip and a link to master
