### ISSUE TITLE
Exporting JWST data - not all spectra in file are saved?

### ISSUE THREAD

**Issue by kassin** [spacetelescope/specviz#647]
When I load one of the simulated JWST data files, 3 spectra display in SpecViz.  However, when I "Export Data," and reload the file, only one spectrum displays.   Were all three spectra saved?

**Comment by nmearl** [comment]
Your currently selected spectrum is the one that gets exported. E.g. if you had a model fitted-spectrum and you wished to export that data.

**Comment by kassin** [comment]
I had all three check boxes selected, so I naively thought all three spectra would be exported.  This needs to be revisited.

**Comment by nmearl** [comment]
Currently, it's a limitation of the export format (we only export as `ecsv` files), which makes it difficult to export more than on spectrum. I think once we properly add-in exporters for various file formats, multiple spectra in one exported file could be supported.

**Comment by drdavella** [comment]
This should not be difficult to support, but we should be clear about expectations. If the sole purpose is to allow data to be saved between `specviz` sessions, then we could simply define a custom writer/loader in specviz that can handle multiple spectra. But if we want the output file to be useful with other tools, we should probably make sure there's a loader in `specutils` that knows how to read the output.

Even if we add a custom writer/loader to `specviz` for this purpose, it doesn't necessarily preclude the possibility of reading it with other tools. We will just need to add some documentation about the format and users will need to know what they're doing.

**Comment by drdavella** [comment]
I actually might argue that this is a great use case for ASDF, but there's some work that would need to be done in `specutils` first in order to support it. I opened an issue there to outline the work that would need to be done: https://github.com/astropy/specutils/issues/442.
