### ISSUE TITLE
Explore handeling FITS image files (dispersion in header WCS) in file loader wizard

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/specviz#661]
Sample files provided through #660.

How do we want to incorporate header WCS into the current file loader wizard?

**Comment by nluetzge** [comment]
This is currently very hard to overcome. I have tried writing my own custom loader not even using the wizard for a fits image spectra and it loads into specutils without a problem but specviz is so set on getting a table that the registry check (I think! I don't really understand it but it uses the astropy.io.regstry there) fails when I give it a none-table fits file ... at least that's what I think is happening...

**Comment by drdavella** [comment]
@nluetzge if you can provide an example file and also the loader you're using, I can try to take a look. This should be possible even if the loader wizard currently doesn't support it.

**Comment by nluetzge** [comment]
@drdavella I'm actually getting the same error now even with a loader I created with the wizard: Its this one:
<img width="388" alt="screen shot 2019-02-13 at 9 36 34 am" src="https://user-images.githubusercontent.com/24398824/52719102-f124aa80-2f72-11e9-8284-68dc34fa68f4.png">

**Comment by drdavella** [comment]
@nluetzge I think I understand where that error is coming from. It's a side-effect of the fix in #640, but it turns out that we're not properly accounting for custom loaders. It would be helpful if you were able to share your data and loader so that I have something to test against.

**Comment by nluetzge** [comment]
@drdavella Ok so do you want the data and loader of the table I'm trying to load or the data and loader of the fits image?

**Comment by drdavella** [comment]
Both would be useful if it's not too difficult. And feel free to share with me over another channel if that's easier.

**Comment by nluetzge** [comment]
Ok cool will contact you on slack
