### ISSUE TITLE
loader wizard not using identifiers

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/specviz#663]
Currently, the loader wizard does not have a way to build identifiers for the output loader file.  With the changes @drdavella made, this means any loader made with the wizard will not auto-load, but always need to be chosen from the drop down loader menu when you use the "load data" button.

We could add an identifier option. However, this may clash in ways the user does not expect with some of the built in loaders.  For example, a user may make a loader with the wizard, and tag the identifier as "all files that end in .fits and start with an 's',. 3 months later they may open a totally different file, say JWST file, that matches that description, forget they made a loader that matches this, and not understand why the JWST loader is not used. Or vice-versa, where a loader is made and one of the pre-built loaders is used instead of the user generated one.

 This is resolved in Astropy by using priorities, which would alleviate most of these issues (including making the user more aware that multiple loaders may match an particular file) however, those are not set up for specutils at the moment as far as I can tell.

thoughts @kassin @hcferguson @nluetzge @gderosa2004 @drdavella @nmearl @eteq

**Comment by hcferguson** [comment]
My feeling is that adding identifiers is a bridge too far for this wizard. In addition to possibly opening up glitches like the one you mention, I think it would be hard enough to explain on the wizard itself that it would confuse most users.

Given how easy it is for someone with basic python skills to write a loader, I would be inclined to try to keep the wizard fairly minimal and refer people to the docs for writing their own loader if they have complex files, or want to make something more general.
