### ISSUE TITLE
specviz file loader crashes for 1D spectrum

### ISSUE THREAD

**Issue by aliciacanipe** [spacetelescope/specviz#672]
**See JIRA ticket: https://jira.stsci.edu/browse/JDA-33**

Data used for testing: A 1D spectrum in ascii format with a column for wavelength and one for the flux.

Data location (if possible): Attached here.

Methods used for testing (e.g., commands or functionalities that were tested): Open specviz from terminal and use both "load data" and "loader wizard".

Traceback for error if applicable: See screenshots attached.

Description of the problem: I tried to load a 1D spectrum in ascii format with the first line as header (both with and without # to comment the line). Specviz returns the message "Could not identify columns containing the wavelength, frequency or energy.". I tried the wizard and I cannot choose the columns. When I close the wizard, it crashes with "Abort trap: 6".

Data and screen shots are in the JIRA ticket above.

**Comment by bsunnquist** [comment]
I also failed to load an ascii table into specviz. I was at least able to preview it correctly in the Loader Wizard, but when I tried to "save to .py" it closed with the exact same error message.

**Comment by aliciacanipe** [comment]
Steve Crawford set up JIRA/GitHub linking. This issue is now being tracked here: https://github.com/spacetelescope/specviz/issues/676 

@nmearl sorry for the trouble -- I'm not sure if you want to close this ticket?
