### ISSUE TITLE
Change data passed into `add_component` to be a glue Component to attach units

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/specviz#679]
From @nmearl in https://github.com/spacetelescope/cubeviz/issues/501#issuecomment-468693750:

> The data passed to the `add_component` method is a simple array-like. This needs to be changed to an explicitly glue `Component` object in order to attached associated units. This would need to be done in specviz's glue data viewer.

**Comment by nmearl** [comment]
Fixed with #680.
