### ISSUE TITLE
autoscale within selected region

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#694]
It would be very handy to have an option to autoscale within a selected region. For one spectrum I've been trying in cubeviz (SINFONI_CAS64_k_bjames) , there are some spurious values on the edge that are in the range 0.1, but the remaining spectrum is ~1.e-19. It's very tedious to scale by hand.

**Comment by nmearl** [comment]
Is the box zoom tool inadequate for this case?
