### ISSUE TITLE
Fix installation procedure

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/specviz#699]
The procedures in the readthedocs installation page fail to install specviz. 

When installing from sources, it finishes the installation procedure, but then the app itself crashes with 
`ModuleNotFoundError: No module named 'specutils.core'`

When pip-installing, an error from numpy (apparently) crashes the install itself: 
`RuntimeError: implement_array_function method already has a docstring`

**Comment by pllim** [comment]
Same reported on Astropy mailing list: https://mail.python.org/pipermail/astropy/2019-September/004582.html

Can one of the maintainers please answer over there? Thanks.

**Comment by nmearl** [comment]
@ibusko how are you installing specviz? You may wish to check your package versions as well:

```python
python -c "import specviz; print(specviz.__version__)"
python -c "import specutils; print(specutils.__version__)"
```

SpecViz should return version 0.7.0, and specutils should return version 0.5.2.

**Comment by ibusko** [comment]
@nmearl I just re-installed everything from scratch, following the readthedocs recipe. I had to do a conda update. And now it works. And the reported versions are correct. 

So maybe the older conda version was the culprit? Interestingly, I hadn't have the alert 'Please update conda by running....' even recently, when creating conda environments on this machine. But the problem seems to have been fixed by itself. I will close this issue.

**Comment by ibusko** [comment]
I will take care of the issue in the astropy mailing list as well.

**Comment by pllim** [comment]
Thanks!
