### ISSUE TITLE
Single tap and (sometimes) hover events cause focus change

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#7]
To reproduce:
- Have two sub windows open
- Single tap over plot area of any sub window
- Sometimes, simply moving focus to a widget outside the MDI area, then hovering over a sub window inside will cause the focus to move to that sub window.

**Comment by pllim** [comment]
I think I am seeing a similar behavior with layers too. I select a layer, then switches focus to a terminal outside Pyfocal, and Pyfocal automatically selects another layer.

**Comment by pllim** [comment]
I vaguely recall you fixed this, right? Can we close this?

**Comment by nmearl** [comment]
I'm not seeing it currently, but I know I did not do anything explicit to solve this problem. We can close for now.
