### ISSUE TITLE
Sub-window can be closed but cannot be re-opened

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#76]
All the sub-windows (e.g., Data, Layers, etc) have their own "x" button to close. However, when I click "x" to close it, there is no way to re-open, so basically I lost the sub-window.

Potential solutions:
1. Remove the "x" button to prevent users from accidentally closing them.
2. Have a way to restore the sub-windows.

**Comment by nmearl** [comment]
We could also have an "Are you sure?" popup dialog.

**Comment by pllim** [comment]
I am not very fond of popup dialogs unless absolutely necessary. I think MS Word and the paperclip spoiled it for me.

**Comment by nmearl** [comment]
I'm not sure this is really an issue. The close button has a very specific purpose, and at some point we have the trust the user to know what they're doing.
