### ISSUE TITLE
Fitting a crazy constant autoscales me out of existence

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#83]
My spectrum has fluxes ~ 4e-15. I picked a constant model and clicked "Add" and then "Create" without tweaking the initial guesses (seems like a fairly common workflow). It autoscaled my spectrum so the range goes from a bit below 0 to a bit above 1 (sensible for the model, but not the data). Currently it doesn't seem like there is an easy to rescale to the data. When I tried just use the trackpad it eventually froze.

**Comment by hcferguson** [comment]
Tried it again, and it autoscaled, but didn't freeze on me. 

I tried to use the context-sensitive menu to manually set the scale. While I'm able to get the context-sensitive menu to come up, I can't get the Y-axis manual-setting sub-menu to stay there when I mouse over it. It just disappears when my mouse leaves the main contextual menu. So I can't manually enter the axis range.

**Comment by pllim** [comment]
@hcferguson , is this still a problem? Just want to make sure since there have been a lot of code updates in the past few weeks.

**Comment by pllim** [comment]
Closing. Feel free to reopen if needed.
