### ISSUE TITLE
Top axis options

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#85]
I suggest the following labels:

- Redshift -> Redshifted
- Channel -> Pixel

Also add a new option: 

- Restframe  -- this would multiply wavelength by 1/(1+z) ....I think this actually will be at least as common as applying a redshift in the forward direction.

**Comment by ibusko** [comment]
What I see in the top axis when loading any of the test spectra is just the speed of light. I suppose that happens because the spectrum has no associated rest frame velocity or anything that can act as a zero point? In that case, shouldn't the axis labels be hidden? Otherwise they just add to the visual clutter.

**Comment by pllim** [comment]
Also see #13

**Comment by nmearl** [comment]
@ibusko The default rest wavelength is 0.0. We can set the default of the axis to be either redshift or channel if velocity isn't defaultly useful.

**Comment by ibusko** [comment]
What about this: setting the axis default to channel would ensure that at least the quantity is varying along the axis. And channel numbers is a property that every digitized spectrum has by definition. In case the spectrum has an associated reference point, then the axis would display a velocity-like quantity. 

How is the redshift / rest frame / reference wavelength property associated with any given spectrum ? Is it input by the user somehow? Does it come with the spectrum already, as in a FITS header keyword or VO SSAP property ?

**Comment by hcferguson** [comment]
+1 for this suggestion. However, I would call it "pixel" or "index". Channel often means something different (e.g. when there are two arms in a spectrograph).

**Comment by nmearl** [comment]
@ibusko There is a pop-up dialog where the user can input the reference wavelength or redshift (it's that first gear icon in the plot window).

I cannot speak to whether or not this information can be withdrawn from the source files directly.

@hcferguson Right. Pixel always made sense to me. I had it that way with the original specview, but it was suggested to use channel somewhere down the line.

**Comment by nmearl** [comment]
See the latest commit 5bcdbdecc3f2bf533c81cb94d50098c434804719.
