### ISSUE TITLE
Is it possible to implement keyboard shortcuts?

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#89]
Lots of GUI tools have keyboard shortcuts that enable expert users to work very fast. IRAF splot commands already give us a good list of what some of the shortcuts might be. Is this possible in pyQtgraph?

**Comment by nmearl** [comment]
Yes, it is possible (through Qt, in fact). If someone wants to come up with a list of preferred keyboard shortcuts, they can be implemented.

**Comment by pllim** [comment]
@ibusko , did the original SpecView have keyboard shortcuts? If so, that's a good starting point. Else, maybe some applicable ones from `specfit` or `splot`.

**Comment by ibusko** [comment]
@pllim No, if you mean the old Java specview.

**Comment by hcferguson** [comment]
Needs elaboration -- i.e. examples of common use cases and possibly standard keyboard shortcuts for these from other tools.
