### ISSUE TITLE
File reader dialog should preserve state of the file type drop-down selector.

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/specviz#90]
It is inconvenient to have to select the same file type over and over when reading multiple files in sequence. The dialog widget defaults to the ASCII type when called; it should preserve whatever selection it had in the previous call. 

I believe that a very common use case is for the user wanting to work with several files that came from a single source, hence share the same format. Based on experience with the java specview, I am sure we are going to get this request from real-world users anyway.

**Comment by pllim** [comment]
That would be nice. If Qt does not support this directly, Pyfocal can probably do one of the following:

* Remember it in a cache file in `~/.pyfocal` that is read in on start up.
* Have user provide their own format order as part of configuration file for GUI customization, not unlike what Ginga does for its GUI.

**Comment by ibusko** [comment]
That would be really nice. Although, if the file type can be preserved within a single session, that would be good too. And maybe easier to implement as a first cut? It could perhaps be implemented just using a global variable to preserve the file type in between calls to the file dialog.
