### ISSUE TITLE
Model initialization

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#91]
It would probably be sensible to initialize models within initial guesses that are not orders of magnitude off. Examples:

- Const: Initialize to the mean in the ROI
- Linear: Slope = 0, Intercept = mean in the ROI
- Gaussian: Estimate moments from the ROI

Simplest not to worry about compound models when initializing.

**Comment by ibusko** [comment]
In the Java specview, I split the models in two types: narrow-band, and wide-band. They were initialized in this way:

- narrow-band: 
  - position: the ROI's mid-point
  - amplitude or height or depth: the ROI's height
  - width: ROI's width divided by a sensible constant (like 3 for a Gaussian, etc.)
  - everything else (Gaussian skew, etc): whatever the default constructor has

- wide-band:
 - reference wavelength: the ROI's mid-point
 - amplitude: the data at the ROI's mid-point
 - everything else (T in blackbody, index in power law, etc): default constructor

This works pretty well in the vast majority of cases.

**Comment by hcferguson** [comment]
Sounds sensible.

**Comment by hcferguson** [comment]
Having changed to regions with infinite vertical extent, @ibusko your suggestion won't work along the flux  axis. I would say you could just compute the mean flux for the data in the region and use that. Not sure if there might be edge cases when there are lots of masked data points or NaNs or if all the values are 0.

**Comment by ibusko** [comment]
The infinite vertical extent poses a potential problem in that the right initialization for the model 'amplitude' or 'height' or whatever parameter might depend on the model type itself. Think of a tiny emission line on top of a very bright continuum. For the continuum initialization, the average flux would work fine, but for the line amplitude it won't. For the line-type models, a range like max(flux)-min(flux) or something in those lines would  probably be better.

**Comment by hcferguson** [comment]
Good point @ibusko. I think generalizing the automatic initialization is never going to be perfect for compound models, but I think even taking the mean would get the initial guess for that narrow emission line at least into the right order of magnitude so that the fitter has a chance of succeeding. If we find on testing that that approach often fails, my next suggestion would be to use the centroid wavelength `w=sum(w*f)/sum(f)` as the center of the line and the flux at the wavelength of that first-moment as the amplitude (assuming amplitude means peak flux...otherwise scale to the integral appropriately to match within the width determined from the second moment `width = sqrt(sum*(w**2*f)/sum(f))` ..and use this width as the first guess for the line width.

I think there will a pretty common use case for compound models where the line is determined from one region and the continuum from others....that will make initialization easier, but we haven't thought about a user interface for that yet.

**Comment by ibusko** [comment]
Modified initialization of line-type models as per @hcferguson suggestion.
